import 'dotenv/config';
import { getNewsItems } from './src/server/newsFeed.js';
const { items } = await getNewsItems();
const now = Date.now();
const age = (i: any) => Math.floor((now - new Date(i.publishedAt).getTime()) / 86400000);
console.log(`\n=== ${items.length} sanitized items ===`);
const bySrc: Record<string, number[]> = {};
for (const i of items) (bySrc[i.source] ??= []).push(age(i));
console.log('\nsource                         n   newest');
for (const [s,a] of Object.entries(bySrc).sort((x,y)=>Math.min(...x[1])-Math.min(...y[1]))) console.log('  '+s.padEnd(28), String(a.length).padStart(2), '  '+Math.min(...a)+'d');
const ages = items.map(age).sort((a,b)=>a-b);
console.log('\nfreshness: newest='+ages[0]+'d median='+ages[Math.floor(ages.length/2)]+'d oldest='+ages[ages.length-1]+'d');
console.log('stale(>21d) or future-dated:', items.filter(i=>age(i)>21||age(i)<-7).length, '(must be 0)');
const byTopic: Record<string, number[]> = {};
for (const i of items) (byTopic[i.topic] ??= []).push(age(i));
console.log('\ntopic       n  newest oldest');
for (const [t,a] of Object.entries(byTopic)) console.log('  '+t.padEnd(10), String(a.length).padStart(2), '  '+Math.min(...a)+'d', '  '+Math.max(...a)+'d');
const cy = items.filter(i=>i.topic==='cyber');
console.log('\ncyber sample:');
for (const c of cy.slice(0,6)) console.log('   '+String(age(c)).padStart(2)+'d', c.source.padEnd(20), c.title.slice(0,52));
console.log('\nwith image:', items.filter(i=>i.image).length+'/'+items.length);
console.log('Kodkod present:', items.some(i=>i.source==='Kodkod Cyber'), '(should be false — all its items are >293d)');
