import JSZip from 'jszip';
import { loadImage, getLogo, loadFont, wrapRtl, BRAND_GREEN } from './newsImageComposer';
import { sanitizeHebrewText } from './hebrewTextSanitizer';
import { highlightCode, TOKEN_PALETTE } from './syntaxHighlight';
import type { TechTipDeck, TechTipSlide, ThreadTheme, ToolBrand } from './techTipsApi';
import { resolveSlidePhotoUrl, loadPhoto } from './pexelsBackground';

/**
 * Tech Tips slide painter — dark-cyber teaching slides, drawn on <canvas> so the SAME painter
 * feeds both outputs: the still carousel PNGs and every frame of the animated reel
 * (motionStudioService.ts). Size-agnostic: pass 1080×1350 for a 4:5 carousel or 1080×1920 for a
 * 9:16 reel and the layout scales off the canvas box rather than hard-coded coordinates.
 *
 * Backgrounds are OPTIONAL and generated by Pollinations (free, keyless, CORS-open — verified) from
 * each slide's own `visualPrompt`. Off by default: generation adds seconds per slide, and every
 * slide already reads correctly on the procedural obsidian+grid backdrop, which is the fallback
 * whenever generation is disabled, slow, or fails.
 */

const OBSIDIAN_TOP = '#09090B';
const OBSIDIAN_BOTTOM = '#0B0C10';
const CYBER_CYAN = '#22D3EE';
const SILVER = '#E2E8F0';
const DOMAIN = 'mrdaniel.co.il';

/** Card surfaces, matching the zinc ramp the rest of the dashboard is built on. */
const ZINC_900 = 'rgba(24,24,27,0.82)';
const ZINC_800 = 'rgba(63,63,70,0.9)';

/**
 * Accent per subject family, assigned by the Threads agent.
 *
 * A deck about Gemini and a deck about ransomware used to render in the identical cyan, so a
 * follower's feed showed one indistinguishable wall of slides. The accent drives the title
 * gradient, the badge and kicker chips, the step badge and the progress rail, which is enough to
 * tell two decks apart at thumbnail size without touching the layout. Every colour here clears
 * 4.5:1 against the obsidian backdrop.
 *
 * A deck that sets no theme (every Tech Tips deck) resolves to 'general' and renders exactly as it
 * did before this table existed.
 */
const THEME_ACCENT: Record<ThreadTheme, string> = {
  ai: CYBER_CYAN,
  automation: BRAND_GREEN,
  security: '#FB923C',
  code: '#A78BFA',
  data: '#38BDF8',
  web3: '#F0ABFC',
  general: BRAND_GREEN,
};

/**
 * Per-tool identity: the wordmark, the accent the slide's chrome is tinted with, and the second
 * colour of the backdrop's glow.
 *
 * A deck about Gemini and a deck about ChatGPT should be distinguishable with the text blurred out,
 * which is exactly how they are seen in a feed. The tool's accent overrides the subject-family
 * accent whenever one was detected, because the tool is the more specific fact about the slide.
 * Every accent here clears 4.5:1 against the obsidian backdrop.
 */
const TOOL_STYLE: Record<ToolBrand, { label: string; accent: string; glow: string }> = {
  gemini: { label: 'Gemini', accent: '#A78BFA', glow: '#22D3EE' },
  chatgpt: { label: 'ChatGPT', accent: '#10D492', glow: '#34D399' },
  claude: { label: 'Claude', accent: '#E08A63', glow: '#F0A882' },
  canva: { label: 'Canva', accent: '#22D3EE', glow: '#A78BFA' },
  notebooklm: { label: 'NotebookLM', accent: '#7AAEFF', glow: '#A78BFA' },
  make: { label: 'Make', accent: '#B98CFF', glow: '#7C3AED' },
  n8n: { label: 'n8n', accent: '#F4708F', glow: '#FB7185' },
  perplexity: { label: 'Perplexity', accent: '#2DD4BF', glow: '#5EEAD4' },
  copilot: { label: 'Copilot', accent: '#A78BFA', glow: '#60A5FA' },
  workspace: { label: 'Workspace', accent: '#7AAEFF', glow: '#34D399' },
  veo: { label: 'Veo', accent: '#7AAEFF', glow: '#A78BFA' },
  midjourney: { label: 'Midjourney', accent: '#E2E8F0', glow: '#94A3B8' },
};

/** The slide's accent: its tool's colour when one was detected, else its subject family's. */
function accentFor(slide: TechTipSlide): string {
  const tool = slide.tool ? TOOL_STYLE[slide.tool] : undefined;
  return tool?.accent ?? THEME_ACCENT[slide.theme ?? 'general'] ?? BRAND_GREEN;
}

/** The second colour of the backdrop glow — the tool's, else a cool counterpoint to the accent. */
function glowFor(slide: TechTipSlide): string {
  const tool = slide.tool ? TOOL_STYLE[slide.tool] : undefined;
  return tool?.glow ?? CYBER_CYAN;
}

export interface SlideBox {
  W: number;
  H: number;
  PAD: number;
}

export function boxFor(width: number, height: number): SlideBox {
  return { W: width, H: height, PAD: Math.round(width * 0.085) };
}

// ─── background ─────────────────────────────────────────────────────────────────────────────

function hexToRgba(hex: string, a: number): string {
  const n = parseInt(hex.replace('#', ''), 16);
  return `rgba(${(n >> 16) & 255},${(n >> 8) & 255},${n & 255},${a})`;
}

function paintProceduralBackground(
  ctx: CanvasRenderingContext2D,
  b: SlideBox,
  seed: number,
  accent: string = BRAND_GREEN,
  glow: string = CYBER_CYAN
) {
  const g = ctx.createLinearGradient(0, 0, b.W * 0.4, b.H);
  g.addColorStop(0, OBSIDIAN_TOP);
  g.addColorStop(1, OBSIDIAN_BOTTOM);
  ctx.fillStyle = g;
  ctx.fillRect(0, 0, b.W, b.H);

  // carbon grid
  ctx.save();
  ctx.strokeStyle = 'rgba(226,232,240,0.035)';
  ctx.lineWidth = 1;
  const step = Math.round(b.W / 10);
  for (let x = step; x < b.W; x += step) {
    ctx.beginPath();
    ctx.moveTo(x + 0.5, 0);
    ctx.lineTo(x + 0.5, b.H);
    ctx.stroke();
  }
  for (let y = step; y < b.H; y += step) {
    ctx.beginPath();
    ctx.moveTo(0, y + 0.5);
    ctx.lineTo(b.W, y + 0.5);
    ctx.stroke();
  }
  ctx.restore();

  // Two ambient glows in the slide's own brand pair, seeded so consecutive slides differ. This is
  // what carries the tool's identity on a photo-free technical slide: a Gemini slide reads
  // purple-into-cyan, a ChatGPT slide emerald, with nothing but the backdrop doing the work.
  const pairs: [string, number, number, number][] = [
    [accent, 0.3 + ((seed * 37) % 40) / 100, 0.24 + ((seed * 53) % 45) / 100, 0.16],
    [glow, 0.72 - ((seed * 29) % 35) / 100, 0.74 - ((seed * 41) % 30) / 100, 0.1],
  ];
  for (const [colour, fx, fy, alpha] of pairs) {
    const cx = b.W * fx;
    const cy = b.H * fy;
    const rg = ctx.createRadialGradient(cx, cy, 0, cx, cy, b.W * 0.78);
    rg.addColorStop(0, hexToRgba(colour, alpha));
    rg.addColorStop(1, 'rgba(0,0,0,0)');
    ctx.fillStyle = rg;
    ctx.fillRect(0, 0, b.W, b.H);
  }
}

// ─── hand-drawn accents ─────────────────────────────────────────────────────────────────────

/**
 * Seeded PRNG. The wobble that makes a stroke read as hand-drawn has to be STABLE: the same slide
 * is painted once for the carousel PNG and again for every frame of the reel, and a random jitter
 * would make the underline crawl across the video.
 */
function rand(seed: number): () => number {
  let s = (seed >>> 0) || 1;
  return () => {
    s = (s * 1664525 + 1013904223) >>> 0;
    return s / 4294967296;
  };
}

/** Strokes a point list as a smooth polyline (midpoint quadratics), so jitter reads as a drawn
 *  line rather than as a jagged one. */
function strokeWobble(ctx: CanvasRenderingContext2D, pts: [number, number][]) {
  if (pts.length < 2) return;
  ctx.beginPath();
  ctx.moveTo(pts[0][0], pts[0][1]);
  for (let i = 1; i < pts.length - 1; i++) {
    const [x, y] = pts[i];
    const [nx, ny] = pts[i + 1];
    ctx.quadraticCurveTo(x, y, (x + nx) / 2, (y + ny) / 2);
  }
  ctx.lineTo(pts[pts.length - 1][0], pts[pts.length - 1][1]);
  ctx.stroke();
}

/** Marker underline beneath a run of text — two passes, the second lighter and offset, which is
 *  what makes a real marker stroke look like one rather than like a border-bottom. */
function scribbleUnderline(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  w: number,
  colour: string,
  seed: number
) {
  if (w <= 0) return;
  const rnd = rand(seed);
  ctx.save();
  ctx.lineCap = 'round';
  ctx.lineJoin = 'round';
  ctx.strokeStyle = colour;
  for (let pass = 0; pass < 2; pass++) {
    ctx.globalAlpha = pass === 0 ? 0.92 : 0.4;
    ctx.lineWidth = Math.max(2, w * (pass === 0 ? 0.016 : 0.009));
    const pts: [number, number][] = [];
    const steps = 9;
    for (let i = 0; i <= steps; i++) {
      const t = i / steps;
      // A drawn underline sags in the middle and overshoots slightly at both ends.
      const sag = Math.sin(t * Math.PI) * w * 0.012;
      pts.push([
        x - w * 0.015 + w * 1.03 * t,
        y + pass * w * 0.016 + sag + (rnd() - 0.5) * w * 0.012,
      ]);
    }
    strokeWobble(ctx, pts);
  }
  ctx.restore();
}

/** Open circle drawn around something — slightly over a full turn, with the overshoot a hand
 *  leaves behind. Used to ring a step numeral. */
function scribbleCircle(
  ctx: CanvasRenderingContext2D,
  cx: number,
  cy: number,
  rx: number,
  ry: number,
  colour: string,
  seed: number
) {
  const rnd = rand(seed);
  ctx.save();
  ctx.lineCap = 'round';
  ctx.strokeStyle = colour;
  ctx.globalAlpha = 0.85;
  ctx.lineWidth = Math.max(2, rx * 0.075);
  const start = -0.7;
  const end = Math.PI * 2 * 1.13 - 0.7;
  const steps = 40;
  const pts: [number, number][] = [];
  for (let i = 0; i <= steps; i++) {
    const a = start + (end - start) * (i / steps);
    const j = 1 + (rnd() - 0.5) * 0.07;
    pts.push([cx + Math.cos(a) * rx * j, cy + Math.sin(a) * ry * j]);
  }
  strokeWobble(ctx, pts);
  ctx.restore();
}

/** Doodle arrow — a curved shaft with a two-stroke head, the kind drawn over a screenshot to say
 *  "this bit". Bows sideways so it never reads as a straight connector. */
function doodleArrow(
  ctx: CanvasRenderingContext2D,
  x1: number,
  y1: number,
  x2: number,
  y2: number,
  colour: string,
  seed: number
) {
  const rnd = rand(seed);
  const dx = x2 - x1;
  const dy = y2 - y1;
  const len = Math.hypot(dx, dy);
  if (len < 4) return;
  ctx.save();
  ctx.lineCap = 'round';
  ctx.lineJoin = 'round';
  ctx.strokeStyle = colour;
  ctx.globalAlpha = 0.9;
  ctx.lineWidth = Math.max(2, len * 0.035);

  // Shaft: bowed perpendicular to the run, plus a little jitter along it.
  const bow = len * 0.22;
  const nx = -dy / len;
  const ny = dx / len;
  const pts: [number, number][] = [];
  const steps = 10;
  for (let i = 0; i <= steps; i++) {
    const t = i / steps;
    const arc = Math.sin(t * Math.PI) * bow;
    pts.push([
      x1 + dx * t + nx * arc + (rnd() - 0.5) * len * 0.02,
      y1 + dy * t + ny * arc + (rnd() - 0.5) * len * 0.02,
    ]);
  }
  strokeWobble(ctx, pts);

  // Head: two strokes off the true tip, angled against the shaft's final direction.
  const [px, py] = pts[pts.length - 2];
  const a = Math.atan2(y2 - py, x2 - px);
  const hl = len * 0.3;
  for (const spread of [2.5, -2.5]) {
    ctx.beginPath();
    ctx.moveTo(x2, y2);
    ctx.lineTo(x2 + Math.cos(a + spread) * hl, y2 + Math.sin(a + spread) * hl);
    ctx.stroke();
  }
  ctx.restore();
}

// ─── tool marks ─────────────────────────────────────────────────────────────────────────────

/**
 * Vector marks for the tools a deck can be about, each drawn into a 0..100 box.
 *
 * Drawn as canvas paths rather than fetched as SVG/PNG on purpose: an external image taints the
 * export canvas and `toDataURL` then throws at the last step of a render that already cost a minute.
 * These are geometric identity marks in each product's own shape language — not reproductions of a
 * trademark — which is also why each one sits next to its wordmark rather than standing alone.
 */
const TOOL_MARKS: Record<ToolBrand, (ctx: CanvasRenderingContext2D, colour: string) => void> = {
  // Four-point sparkle.
  gemini: (ctx, c) => {
    ctx.fillStyle = c;
    ctx.fill(
      new Path2D(
        'M50 2C50 28 28 50 2 50C28 50 50 72 50 98C50 72 72 50 98 50C72 50 50 28 50 2Z'
      )
    );
  },
  // Interlocking loops — three stroked ellipses at 60° to each other.
  chatgpt: (ctx, c) => {
    ctx.strokeStyle = c;
    ctx.lineWidth = 8;
    for (let i = 0; i < 3; i++) {
      ctx.beginPath();
      ctx.ellipse(50, 50, 46, 22, (i * Math.PI) / 3, 0, Math.PI * 2);
      ctx.stroke();
    }
  },
  // Radiating burst.
  claude: (ctx, c) => {
    ctx.strokeStyle = c;
    ctx.lineCap = 'round';
    ctx.lineWidth = 8;
    for (let i = 0; i < 11; i++) {
      const a = (i / 11) * Math.PI * 2;
      const inner = 14;
      const outer = i % 2 === 0 ? 47 : 38;
      ctx.beginPath();
      ctx.moveTo(50 + Math.cos(a) * inner, 50 + Math.sin(a) * inner);
      ctx.lineTo(50 + Math.cos(a) * outer, 50 + Math.sin(a) * outer);
      ctx.stroke();
    }
  },
  // Open ring in the shape of a C.
  canva: (ctx, c) => {
    ctx.strokeStyle = c;
    ctx.lineCap = 'round';
    ctx.lineWidth = 13;
    ctx.beginPath();
    ctx.arc(50, 50, 38, Math.PI * 0.35, Math.PI * 1.68);
    ctx.stroke();
  },
  // Notebook with a spark.
  notebooklm: (ctx, c) => {
    ctx.strokeStyle = c;
    ctx.lineCap = 'round';
    ctx.lineWidth = 8;
    roundRectPath(ctx, 14, 10, 62, 80, 12);
    ctx.stroke();
    ctx.beginPath();
    for (const y of [34, 50]) {
      ctx.moveTo(30, y);
      ctx.lineTo(60, y);
    }
    ctx.stroke();
    ctx.fillStyle = c;
    ctx.fill(new Path2D('M76 44C76 56 68 64 56 64C68 64 76 72 76 84C76 72 84 64 96 64C84 64 76 56 76 44Z'));
  },
  // Two chevrons forming an M.
  make: (ctx, c) => {
    ctx.strokeStyle = c;
    ctx.lineCap = 'round';
    ctx.lineJoin = 'round';
    ctx.lineWidth = 11;
    ctx.beginPath();
    ctx.moveTo(14, 78);
    ctx.lineTo(32, 22);
    ctx.lineTo(50, 62);
    ctx.lineTo(68, 22);
    ctx.lineTo(86, 78);
    ctx.stroke();
  },
  // Connected nodes — one source fanning into two.
  n8n: (ctx, c) => {
    ctx.strokeStyle = c;
    ctx.lineWidth = 7;
    ctx.beginPath();
    ctx.moveTo(26, 50);
    ctx.lineTo(52, 50);
    ctx.moveTo(52, 50);
    ctx.lineTo(74, 26);
    ctx.moveTo(52, 50);
    ctx.lineTo(74, 74);
    ctx.stroke();
    ctx.fillStyle = c;
    for (const [x, y, r] of [
      [20, 50, 12],
      [78, 24, 10],
      [78, 76, 10],
    ]) {
      ctx.beginPath();
      ctx.arc(x, y, r, 0, Math.PI * 2);
      ctx.fill();
    }
  },
  // Branching search glyph.
  perplexity: (ctx, c) => {
    ctx.strokeStyle = c;
    ctx.lineCap = 'round';
    ctx.lineWidth = 8;
    ctx.beginPath();
    ctx.moveTo(50, 10);
    ctx.lineTo(50, 90);
    ctx.moveTo(50, 30);
    ctx.lineTo(18, 30);
    ctx.lineTo(18, 62);
    ctx.moveTo(50, 30);
    ctx.lineTo(82, 30);
    ctx.lineTo(82, 62);
    ctx.stroke();
  },
  // Goggled mark.
  copilot: (ctx, c) => {
    ctx.strokeStyle = c;
    ctx.lineWidth = 8;
    roundRectPath(ctx, 10, 28, 80, 46, 23);
    ctx.stroke();
    ctx.fillStyle = c;
    for (const x of [36, 64]) {
      ctx.beginPath();
      ctx.ellipse(x, 51, 9, 11, 0, 0, Math.PI * 2);
      ctx.fill();
    }
  },
  // Four-arc ring, the Google family device.
  workspace: (ctx, c) => {
    ctx.lineCap = 'butt';
    ctx.lineWidth = 13;
    const arcs: [string, number, number][] = [
      ['#4285F4', -0.35, 1.2],
      ['#EA4335', 1.3, 2.7],
      ['#FBBC05', 2.8, 4.2],
      ['#34A853', 4.3, 5.85],
    ];
    for (const [colour, a0, a1] of arcs) {
      ctx.strokeStyle = colour || c;
      ctx.beginPath();
      ctx.arc(50, 50, 38, a0, a1);
      ctx.stroke();
    }
  },
  // Play glyph with a spark.
  veo: (ctx, c) => {
    ctx.strokeStyle = c;
    ctx.lineWidth = 8;
    roundRectPath(ctx, 8, 20, 72, 60, 16);
    ctx.stroke();
    ctx.fillStyle = c;
    ctx.beginPath();
    ctx.moveTo(36, 34);
    ctx.lineTo(64, 50);
    ctx.lineTo(36, 66);
    ctx.closePath();
    ctx.fill();
    ctx.fill(new Path2D('M84 8C84 18 78 24 68 24C78 24 84 30 84 40C84 30 90 24 100 24C90 24 84 18 84 8Z'));
  },
  // Sail over a hull.
  midjourney: (ctx, c) => {
    ctx.strokeStyle = c;
    ctx.lineCap = 'round';
    ctx.lineJoin = 'round';
    ctx.lineWidth = 8;
    ctx.beginPath();
    ctx.moveTo(50, 12);
    ctx.lineTo(50, 66);
    ctx.moveTo(50, 20);
    ctx.lineTo(84, 66);
    ctx.lineTo(50, 66);
    ctx.stroke();
    ctx.beginPath();
    ctx.moveTo(16, 74);
    ctx.quadraticCurveTo(50, 96, 88, 74);
    ctx.stroke();
  },
};

/** Paints a tool's mark into a `size`×`size` box at (x, y). */
function drawToolMark(ctx: CanvasRenderingContext2D, tool: ToolBrand, x: number, y: number, size: number, colour: string) {
  const mark = TOOL_MARKS[tool];
  if (!mark) return;
  ctx.save();
  ctx.translate(x, y);
  ctx.scale(size / 100, size / 100);
  ctx.lineCap = 'round';
  ctx.lineJoin = 'round';
  mark(ctx, colour);
  ctx.restore();
}

/** Pollinations: free + keyless + `Access-Control-Allow-Origin: *` (verified), so the generated
 * image can be drawn to canvas without tainting it. */
export function pollinationsUrl(prompt: string, width: number, height: number, seed: number): string {
  const p = encodeURIComponent(prompt.slice(0, 380));
  return `https://image.pollinations.ai/prompt/${p}?width=${width}&height=${height}&nologo=true&seed=${seed}`;
}

/** Resolves one AI backdrop per slide. Bounded concurrency + per-image timeout; any failure just
 * yields null and the slide falls back to the procedural backdrop. */
/**
 * Technologies whose logos meaningfully sharpen an illustration.
 *
 * A generic "abstract tech grid" backdrop is interchangeable between guides. Naming the actual
 * stack in the image prompt — the Python emblem, the Docker whale — anchors the illustration to
 * the subject and makes the set read as one deliberate series rather than stock filler.
 * Matched case-insensitively on word boundaries so "Go" does not fire on "Google".
 */
const BRAND_TERMS: { re: RegExp; visual: string }[] = [
  { re: /\bpython\b/i, visual: 'Python logo emblem, blue and yellow entwined serpents' },
  { re: /\bdocker\b/i, visual: 'Docker whale logo carrying shipping containers' },
  { re: /\b(kubernetes|k8s)\b/i, visual: 'Kubernetes blue helm wheel logo' },
  { re: /\breact\b/i, visual: 'React atom orbital logo in cyan' },
  { re: /\bnode(\.js)?\b/i, visual: 'Node.js green hexagon logo' },
  { re: /\b(typescript|ts)\b/i, visual: 'TypeScript blue square TS logo' },
  { re: /\bpostgres(ql)?\b/i, visual: 'PostgreSQL blue elephant logo' },
  { re: /\bmongo(db)?\b/i, visual: 'MongoDB green leaf logo' },
  { re: /\bredis\b/i, visual: 'Redis red stacked cubes logo' },
  { re: /\b(aws|amazon web services)\b/i, visual: 'AWS orange logo above a cloud datacenter' },
  { re: /\bazure\b/i, visual: 'Microsoft Azure blue triangle logo' },
  { re: /\bgit(hub)?\b/i, visual: 'GitHub Octocat logo with branching version control graph' },
  { re: /\b(linux|ubuntu)\b/i, visual: 'Linux Tux penguin logo beside a terminal' },
  { re: /\bnginx\b/i, visual: 'NGINX green N logo' },
  { re: /\b(tensorflow|pytorch)\b/i, visual: 'machine learning framework logo over a neural network' },
  { re: /\b(openai|gpt)\b/i, visual: 'OpenAI hexagonal knot emblem' },
  { re: /\bfigma\b/i, visual: 'Figma multicoloured shapes logo' },
  { re: /\bterraform\b/i, visual: 'Terraform purple T logo, infrastructure as code' },
];

/** Brand/tech visuals named anywhere in the slide's own text. */
function brandVisualsFor(text: string): string[] {
  return BRAND_TERMS.filter((t) => t.re.test(text)).map((t) => t.visual).slice(0, 3);
}

/**
 * Background sources offered in the Tips & Guides control bar.
 *
 * `creator` is the odd one out and deliberately so: it fetches nothing at all. The deck is painted
 * on the procedural obsidian backdrop lit by the slide's own tool colours, which is what the
 * reference aesthetic actually is — a stock photo behind a prompt card is the thing it avoids.
 */
export type TipStyle = 'creator' | 'photoreal' | 'enterprise' | 'dark-minimal' | 'sketchnote';

/** Extra search terms per style, appended to the slide's own contextual query. */
const STYLE_TONE: Record<TipStyle, string> = {
  creator: '',
  photoreal: 'professional photography',
  enterprise: 'bright clean corporate office technology',
  'dark-minimal': 'dark moody minimal technology',
  sketchnote: '',
};

export async function resolveTipBackgrounds(
  deck: TechTipDeck,
  width: number,
  height: number,
  onProgress?: (done: number, total: number) => void,
  style: TipStyle = 'photoreal'
): Promise<(HTMLImageElement | null)[]> {
  const total = deck.slides.length;
  const out: (HTMLImageElement | null)[] = new Array(total).fill(null);
  let done = 0;
  let cursor = 0;
  // Tracks fallback photos already used so two slides never land on the same stock image.
  const usedFallbacks = new Set<number>();
  const workers = Array.from({ length: Math.min(3, total) }, async () => {
    while (cursor < total) {
      const i = cursor++;
      const slide = deck.slides[i];
      if (slide.sourceImage) {
        // An image the thread itself published beats anything generated or searched: it is what the
        // post actually showed, so it can't be off-topic. Already routed through the site's own
        // relay by the fetcher, so it draws to canvas without tainting it. A failure yields null
        // and the slide falls back to the procedural backdrop, same as every other source here.
        out[i] = await loadPhoto(slide.sourceImage, 12000);
      } else if (style === 'creator' || slide.noPhoto) {
        // Zero stock imagery. `noPhoto` marks the slides carrying something the reader is meant to
        // copy, run or click; `creator` applies the same rule to the whole deck. Either way the
        // slide keeps the procedural backdrop, lit in its own tool's colours — which is the point,
        // not a fallback.
        out[i] = null;
      } else if (style === 'sketchnote') {
        // Illustrated art: keep the existing Pollinations path driven by the slide's visualPrompt.
        const subject = [slide.title, slide.body, slide.code].filter(Boolean).join(' ');
        const brands = brandVisualsFor(subject);
        const prompt = [
          slide.visualPrompt || 'dark cyber technology scene, neon green accents',
          ...brands,
          // Pushes the model off generic wallpaper and towards a deliberate, readable illustration.
          'bold high-contrast digital illustration, dramatic rim lighting, deep dark background,',
          'sharp focal subject, cinematic depth, no text, no letters, no watermark',
        ].join(', ');
        out[i] = await Promise.race([
          loadImage(pollinationsUrl(prompt, Math.round(width / 2), Math.round(height / 2), i + 7)),
          new Promise<null>((r) => setTimeout(() => r(null), 30000)),
        ]);
      } else {
        // Photographic styles: build the query from THIS slide's own text, not the deck title, so
        // each slide gets its own matched image. resolveSlidePhotoUrl sends the slide text to the
        // server, which derives a targeted English scene query for it.
        const slideText = [slide.title, slide.body, slide.visualPrompt]
          .filter(Boolean).join(' ').slice(0, 320);
        const orientation = height > width ? 'portrait' : height === width ? 'square' : 'landscape';
        const url = await resolveSlidePhotoUrl(
          `${slideText} ${STYLE_TONE[style]}`.trim(),
          deck.title || slide.title || 'technology',
          orientation,
          i + 7,
          usedFallbacks
        );
        out[i] = await Promise.race([
          loadPhoto(url, 12000),
          new Promise<null>((r) => setTimeout(() => r(null), 15000)),
        ]);
      }
      done++;
      onProgress?.(done, total);
    }
  });
  await Promise.all(workers);
  return out;
}

function drawBackgroundImage(ctx: CanvasRenderingContext2D, b: SlideBox, img: HTMLImageElement) {
  const iw = img.naturalWidth;
  const ih = img.naturalHeight;
  if (!iw || !ih) return;
  const canvasRatio = b.W / b.H;
  const imgRatio = iw / ih;
  let sw: number, sh: number, sx: number, sy: number;
  if (imgRatio > canvasRatio) {
    sh = ih;
    sw = sh * canvasRatio;
    sx = (iw - sw) / 2;
    sy = 0;
  } else {
    sw = iw;
    sh = sw / canvasRatio;
    sx = 0;
    sy = (ih - sh) / 2;
  }
  ctx.drawImage(img, sx, sy, sw, sh, 0, 0, b.W, b.H);
  // Heavy scrim: the AI backdrop is texture, never competition for the teaching content.
  ctx.fillStyle = 'rgba(6,8,13,0.78)';
  ctx.fillRect(0, 0, b.W, b.H);
}

// ─── chrome ─────────────────────────────────────────────────────────────────────────────────

function roundRectPath(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, r: number) {
  const rr = Math.max(0, Math.min(r, w / 2, h / 2));
  ctx.beginPath();
  ctx.moveTo(x + rr, y);
  ctx.arcTo(x + w, y, x + w, y + h, rr);
  ctx.arcTo(x + w, y + h, x, y + h, rr);
  ctx.arcTo(x, y + h, x, y, rr);
  ctx.arcTo(x, y, x + w, y, rr);
  ctx.closePath();
}

function glassPanel(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, r: number, accent?: string) {
  ctx.save();
  ctx.shadowColor = 'rgba(0,0,0,0.5)';
  ctx.shadowBlur = 36;
  ctx.shadowOffsetY = 18;
  roundRectPath(ctx, x, y, w, h, r);
  ctx.fillStyle = 'rgba(255,255,255,0.035)';
  ctx.fill();
  ctx.restore();
  roundRectPath(ctx, x, y, w, h, r);
  ctx.strokeStyle = accent ? hexToRgba(accent, 0.35) : 'rgba(255,255,255,0.10)';
  ctx.lineWidth = 1.5;
  ctx.stroke();
}

const setDisplay = (ctx: CanvasRenderingContext2D, px: number, w = 800) => {
  ctx.font = `${w} ${Math.round(px)}px Rubik, Heebo, sans-serif`;
};
const setBody = (ctx: CanvasRenderingContext2D, px: number, w = 400) => {
  ctx.font = `${w} ${Math.round(px)}px Heebo, Rubik, sans-serif`;
};
const setMono = (ctx: CanvasRenderingContext2D, px: number, w = 500) => {
  ctx.font = `${w} ${Math.round(px)}px 'JetBrains Mono', 'Heebo', monospace`;
};

function autoFit(
  ctx: CanvasRenderingContext2D,
  text: string,
  maxW: number,
  startPx: number,
  minPx: number,
  maxLines: number,
  set: (c: CanvasRenderingContext2D, px: number) => void
): { lines: string[]; px: number } {
  let px = startPx;
  let lines: string[] = [];
  for (let i = 0; i < 24; i++) {
    set(ctx, px);
    lines = wrapRtl(ctx, text, maxW);
    if (lines.length <= maxLines || px <= minPx) break;
    px = Math.max(minPx, px * 0.93);
  }
  return { lines, px };
}

function drawTopBar(
  ctx: CanvasRenderingContext2D,
  b: SlideBox,
  slide: TechTipSlide,
  index: number,
  total: number,
  logo: HTMLImageElement | null,
  accent: string
) {
  const y = Math.round(b.H * 0.045);
  // Progress, left (LTR). A Threads deck counts the SUB-POSTS it was built from ("2 / 7"), which is
  // the sequence the reader is actually stepping through; a deck with no sub-posts keeps the
  // deck-wide slide index it always showed.
  const progress =
    slide.stepLabel?.trim() || `${String(index + 1).padStart(2, '0')} / ${String(total).padStart(2, '0')}`;
  ctx.save();
  ctx.direction = 'ltr';
  ctx.textAlign = 'left';
  ctx.textBaseline = 'middle';
  setMono(ctx, b.W * 0.019, 600);
  ctx.fillStyle = 'rgba(226,232,240,0.55)';
  ctx.fillText(progress, b.PAD, y);
  const progressW = ctx.measureText(progress).width;
  ctx.restore();

  // Topic badge, beside the counter. Latin by design — "Gemini AI", not a transliteration — so it
  // is drawn LTR next to the LTR counter rather than in the RTL lane on the right.
  const badge = (slide.badge ?? '').trim();
  if (badge) {
    ctx.save();
    ctx.direction = 'ltr';
    ctx.textAlign = 'left';
    ctx.textBaseline = 'middle';
    setMono(ctx, b.W * 0.0165, 700);
    const bh = b.W * 0.034;
    // The tool's mark rides inside the topic chip as a leading glyph rather than claiming a lane of
    // its own — the top bar already carries a counter, the chip and the site logo, and a fourth
    // element there crowds the slide at thumbnail size.
    const markS = slide.tool ? bh * 0.74 : 0;
    const markGap = slide.tool ? b.W * 0.009 : 0;
    const bw = ctx.measureText(badge).width + b.W * 0.03 + markS + markGap;
    const bx = b.PAD + progressW + b.W * 0.022;
    roundRectPath(ctx, bx, y - bh / 2, bw, bh, bh * 0.3);
    ctx.fillStyle = hexToRgba(accent, 0.14);
    ctx.fill();
    ctx.strokeStyle = hexToRgba(accent, 0.5);
    ctx.lineWidth = 1;
    ctx.stroke();
    if (slide.tool) drawToolMark(ctx, slide.tool, bx + b.W * 0.013, y - markS / 2, markS, accent);
    ctx.fillStyle = accent;
    ctx.fillText(badge, bx + b.W * 0.015 + markS + markGap, y + 1);
    ctx.restore();
  }

  // kicker chip, right (RTL)
  const kicker = sanitizeHebrewText(slide.kicker || '');
  if (kicker) {
    ctx.save();
    ctx.direction = 'rtl';
    ctx.textAlign = 'right';
    ctx.textBaseline = 'middle';
    setMono(ctx, b.W * 0.018, 600);
    const kw = ctx.measureText(kicker).width + b.W * 0.035;
    const kh = b.W * 0.038;
    const kx = b.W - b.PAD - kw;
    roundRectPath(ctx, kx, y - kh / 2, kw, kh, kh * 0.28);
    ctx.fillStyle = hexToRgba(accent, 0.12);
    ctx.fill();
    ctx.strokeStyle = hexToRgba(accent, 0.45);
    ctx.lineWidth = 1;
    ctx.stroke();
    ctx.fillStyle = accent;
    ctx.fillText(kicker, b.W - b.PAD - b.W * 0.017, y + 1);
    ctx.restore();
  }

  if (logo) {
    const h = b.W * 0.032;
    const w = h * (logo.naturalWidth / logo.naturalHeight || 3);
    ctx.save();
    ctx.globalAlpha = 0.85;
    ctx.drawImage(logo, b.W / 2 - w / 2, y - h / 2, w, h);
    ctx.restore();
  }
}

function drawBottomBar(ctx: CanvasRenderingContext2D, b: SlideBox, index: number, total: number, accent: string) {
  const railY = b.H - b.PAD * 1.15;
  const gap = 7;
  const railW = b.W - b.PAD * 2;
  const segW = (railW - gap * (total - 1)) / total;
  for (let i = 0; i < total; i++) {
    const x = b.PAD + i * (segW + gap);
    roundRectPath(ctx, x, railY, Math.max(2, segW), 5, 2.5);
    ctx.fillStyle = i <= index ? accent : 'rgba(255,255,255,0.14)';
    ctx.fill();
  }
  ctx.save();
  ctx.direction = 'ltr';
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';
  setMono(ctx, b.W * 0.019, 600);
  ctx.fillStyle = 'rgba(226,232,240,0.6)';
  ctx.fillText(DOMAIN, b.W / 2, b.H - b.PAD * 0.5);
  ctx.restore();
}

// ─── per-kind bodies ────────────────────────────────────────────────────────────────────────

interface Region {
  x: number;
  y: number;
  w: number;
  h: number;
}

function contentRegion(b: SlideBox): Region {
  const top = b.H * 0.14;
  const bottom = b.H - b.PAD * 1.9;
  return { x: b.PAD, y: top, w: b.W - b.PAD * 2, h: bottom - top };
}

function drawTitle(ctx: CanvasRenderingContext2D, b: SlideBox, r: Region, title: string, startPx: number, maxLines: number, accent: string): number {
  if (!title) return r.y;
  const { lines, px } = autoFit(ctx, sanitizeHebrewText(title), r.w, startPx, b.W * 0.032, maxLines, (c, p) => setDisplay(c, p, 800));
  setDisplay(ctx, px, 800);
  ctx.direction = 'rtl';
  ctx.textAlign = 'right';
  ctx.textBaseline = 'alphabetic';
  let y = r.y + px;
  for (const line of lines) {
    const grad = ctx.createLinearGradient(r.x + r.w, 0, r.x, 0);
    grad.addColorStop(0, '#FFFFFF');
    grad.addColorStop(0.6, SILVER);
    grad.addColorStop(1, accent);
    ctx.fillStyle = grad;
    ctx.fillText(line, r.x + r.w, y);
    y += px * 1.18;
  }
  return y;
}

function drawParagraph(ctx: CanvasRenderingContext2D, b: SlideBox, r: Region, text: string, top: number, maxH: number) {
  if (!text) return;
  const { lines, px } = autoFit(ctx, sanitizeHebrewText(text), r.w - b.W * 0.06, b.W * 0.038, b.W * 0.022, 14, (c, p) => setBody(c, p, 400));
  const lh = px * 1.55;
  const panelH = Math.min(maxH, lines.length * lh + b.W * 0.075);
  glassPanel(ctx, r.x, top, r.w, panelH, b.W * 0.028);
  setBody(ctx, px, 400);
  ctx.fillStyle = 'rgba(255,255,255,0.94)';
  ctx.direction = 'rtl';
  ctx.textAlign = 'right';
  let y = top + b.W * 0.045 + px;
  for (const line of lines) {
    if (y > top + panelH - b.W * 0.01) break;
    ctx.fillText(line, r.x + r.w - b.W * 0.03, y);
    y += lh;
  }
}

function drawCodeBlock(ctx: CanvasRenderingContext2D, b: SlideBox, r: Region, slide: TechTipSlide, top: number, maxH: number) {
  const lines = highlightCode(slide.code, slide.codeLang);
  const panelH = maxH;
  glassPanel(ctx, r.x, top, r.w, panelH, b.W * 0.024, CYBER_CYAN);

  // window chrome + language tag
  ctx.save();
  for (let i = 0; i < 3; i++) {
    ctx.beginPath();
    ctx.arc(r.x + b.W * 0.032 + i * b.W * 0.022, top + b.W * 0.032, b.W * 0.0055, 0, Math.PI * 2);
    ctx.fillStyle = ['#F87171', '#FBBF24', '#34D399'][i];
    ctx.fill();
  }
  ctx.direction = 'ltr';
  ctx.textAlign = 'right';
  ctx.textBaseline = 'middle';
  setMono(ctx, b.W * 0.017, 700);
  ctx.fillStyle = hexToRgba(CYBER_CYAN, 0.85);
  ctx.fillText((slide.codeLang || 'code').toUpperCase(), r.x + r.w - b.W * 0.028, top + b.W * 0.032);
  ctx.restore();

  // Fit the snippet. Shrinking alone was not enough: once the floor size was reached a long line
  // simply kept overflowing the terminal border (the slide-03 bug), because nothing ever wrapped.
  // Now the width budget is enforced by WRAPPING at the token level after shrinking, and the panel
  // is clipped as a final guarantee that no glyph can paint outside the box.
  const innerTop = top + b.W * 0.062;
  const innerH = panelH - b.W * 0.078;
  const innerX = r.x + b.W * 0.028;
  const innerW = r.w - b.W * 0.075;

  let px = b.W * 0.026;
  const minPx = b.W * 0.0135;
  let wrapped: { toks: { text: string; color: keyof typeof TOKEN_PALETTE }[]; num: number | null }[] = [];

  for (let i = 0; i < 24; i++) {
    setMono(ctx, px, 500);
    const gutter = px * 2.2;
    const textW = innerW - gutter;
    wrapped = wrapCodeLines(ctx, lines, textW);
    if ((wrapped.length * px * 1.5 <= innerH && maxTokenWidth(ctx, wrapped) <= textW) || px <= minPx) break;
    px = Math.max(minPx, px * 0.94);
  }
  setMono(ctx, px, 500);
  const lh = px * 1.5;
  const gutterW = px * 2.2;

  ctx.save();
  // Hard clip to the panel interior — belt and braces against any residual overflow.
  ctx.beginPath();
  ctx.rect(innerX - px * 0.3, innerTop - px, innerW + px * 0.6, innerH + px);
  ctx.clip();
  ctx.direction = 'ltr';
  ctx.textAlign = 'left';
  ctx.textBaseline = 'alphabetic';
  let y = innerTop + px;
  for (const row of wrapped) {
    if (y > innerTop + innerH) break;
    if (row.num !== null) {
      ctx.fillStyle = 'rgba(148,163,184,0.35)';
      ctx.fillText(String(row.num).padStart(2, ' '), innerX, y);
    }
    // Continuation rows indent slightly so a wrapped line reads as one statement.
    let x = innerX + gutterW + (row.num === null ? px * 1.2 : 0);
    for (const tok of row.toks) {
      ctx.fillStyle = TOKEN_PALETTE[tok.color];
      ctx.fillText(tok.text, x, y);
      x += ctx.measureText(tok.text).width;
    }
    y += lh;
  }
  ctx.restore();
}

/** Widest rendered row, used by the fit loop. */
function maxTokenWidth(
  ctx: CanvasRenderingContext2D,
  rows: { toks: { text: string; color: keyof typeof TOKEN_PALETTE }[] }[]
): number {
  return rows.reduce(
    (m, row) => Math.max(m, ctx.measureText(row.toks.map((t) => t.text).join('')).width),
    0
  );
}

/**
 * Wraps highlighted code lines to a pixel width, preserving token colours.
 *
 * Splits on token boundaries first and only breaks inside a token when a single token is itself
 * wider than the budget (a long URL or path), so syntax colouring survives the wrap. Continuation
 * rows carry `num: null` so the line-number gutter is not repeated.
 */
function wrapCodeLines(
  ctx: CanvasRenderingContext2D,
  lines: { text: string; color: keyof typeof TOKEN_PALETTE }[][],
  maxW: number
): { toks: { text: string; color: keyof typeof TOKEN_PALETTE }[]; num: number | null }[] {
  const out: { toks: { text: string; color: keyof typeof TOKEN_PALETTE }[]; num: number | null }[] = [];
  if (maxW <= 0) return out;

  lines.forEach((toks, idx) => {
    let row: { text: string; color: keyof typeof TOKEN_PALETTE }[] = [];
    let rowW = 0;
    let first = true;
    const push = () => {
      out.push({ toks: row, num: first ? idx + 1 : null });
      first = false;
      row = [];
      rowW = 0;
    };

    for (const tok of toks) {
      let text = tok.text;
      while (text) {
        const w = ctx.measureText(text).width;
        if (rowW + w <= maxW) {
          row.push({ text, color: tok.color });
          rowW += w;
          break;
        }
        // Find how much of this token still fits on the current row.
        let fit = text.length;
        while (fit > 0 && rowW + ctx.measureText(text.slice(0, fit)).width > maxW) fit--;
        if (fit === 0) {
          if (row.length === 0) fit = 1; // pathological: force at least one char to avoid a stall
          else {
            push();
            continue;
          }
        }
        row.push({ text: text.slice(0, fit), color: tok.color });
        text = text.slice(fit);
        push();
      }
    }
    if (row.length > 0 || first) push();
  });

  return out;
}

/**
 * Plain greedy word wrap for Latin text. `wrapRtl` is tuned for Hebrew shaping; a quoted prompt is
 * usually English and only needs word breaking, with blank lines preserved as paragraph breaks.
 */
function wrapLtr(ctx: CanvasRenderingContext2D, text: string, maxW: number): string[] {
  const out: string[] = [];
  for (const para of text.split('\n')) {
    let line = '';
    for (const word of para.split(/\s+/).filter(Boolean)) {
      const next = line ? `${line} ${word}` : word;
      if (!line || ctx.measureText(next).width <= maxW) {
        line = next;
      } else {
        out.push(line);
        line = word;
      }
    }
    out.push(line);
  }
  return out;
}

/**
 * A prompt lifted from the source thread, in its own dark copyable container.
 *
 * Deliberately not drawCodeBlock: a prompt is text to COPY into a model, not source to read, so it
 * gets a plain slab with a copy affordance and no line numbers or syntax colouring — tokenising
 * English prose as if it were code makes it harder to read, not easier. Direction follows the
 * prompt's own script, so a Hebrew prompt is not painted left-to-right.
 */
function drawPromptBox(
  ctx: CanvasRenderingContext2D,
  b: SlideBox,
  r: Region,
  raw: string,
  top: number,
  maxH: number,
  accent: string
) {
  const clean = raw.trim();
  if (!clean || maxH <= 0) return;
  const rtl = /[֐-׿]/.test(clean.slice(0, 80));

  // The card is MEASURED before it is drawn: a prompt that needs four lines gets a four-line card,
  // not one stretched to the bottom of the slide. Sizing it to the region left short prompts
  // floating in a half-empty slab, which reads as a rendering fault rather than as a design.
  const headPad = b.W * 0.034;
  const gapBelowHead = b.W * 0.032;
  const bottomPad = b.W * 0.026;
  const chromeH = headPad + gapBelowHead + bottomPad;
  const innerW = r.w - b.W * 0.06;
  const budget = maxH - chromeH;
  if (budget <= 0) return;

  let px = b.W * 0.026;
  const minPx = b.W * 0.015;
  let lines: string[] = [];
  for (let i = 0; i < 24; i++) {
    setMono(ctx, px, 400);
    lines = rtl ? wrapRtl(ctx, sanitizeHebrewText(clean), innerW) : wrapLtr(ctx, clean, innerW);
    if (lines.length * px * 1.5 <= budget || px <= minPx) break;
    px = Math.max(minPx, px * 0.94);
  }
  setMono(ctx, px, 400);
  // A prompt too long even at the floor size is clipped, not allowed to grow the card past maxH.
  const textH = Math.min(budget, lines.length * px * 1.5);
  const panelH = chromeH + textH;

  // Glassmorphic dark card: a zinc-900 slab on a zinc-800 hairline, lifted off the backdrop by its
  // own drop shadow, with the accent reserved for the top edge and the PROMPT tag. The card used to
  // be outlined entirely in the accent, which made every prompt shout as loudly as the title.
  const radius = b.W * 0.024;
  ctx.save();
  ctx.shadowColor = 'rgba(0,0,0,0.55)';
  ctx.shadowBlur = 40;
  ctx.shadowOffsetY = 20;
  roundRectPath(ctx, r.x, top, r.w, panelH, radius);
  ctx.fillStyle = ZINC_900;
  ctx.fill();
  ctx.restore();
  ctx.save();
  roundRectPath(ctx, r.x, top, r.w, panelH, radius);
  ctx.strokeStyle = ZINC_800;
  ctx.lineWidth = 1.5;
  ctx.stroke();
  // Accent hairline along the top edge, clipped to the card so it follows the corner radius.
  roundRectPath(ctx, r.x, top, r.w, panelH, radius);
  ctx.clip();
  ctx.fillStyle = hexToRgba(accent, 0.75);
  ctx.fillRect(r.x, top, r.w, Math.max(2, b.W * 0.0028));
  ctx.restore();

  // header: the PROMPT tag, plus the two-offset-squares mark that reads universally as "copy"
  const headY = top + headPad;
  ctx.save();
  ctx.direction = 'ltr';
  ctx.textBaseline = 'middle';
  ctx.textAlign = 'left';
  setMono(ctx, b.W * 0.017, 700);
  ctx.fillStyle = hexToRgba(accent, 0.9);
  ctx.fillText('PROMPT', r.x + b.W * 0.03, headY);
  const gs = b.W * 0.022;
  const gx = r.x + r.w - b.W * 0.03 - gs;
  ctx.strokeStyle = hexToRgba(accent, 0.6);
  ctx.lineWidth = Math.max(1.4, b.W * 0.002);
  roundRectPath(ctx, gx + gs * 0.28, headY - gs * 0.64, gs * 0.72, gs * 0.72, gs * 0.16);
  ctx.stroke();
  roundRectPath(ctx, gx, headY - gs * 0.26, gs * 0.72, gs * 0.72, gs * 0.16);
  ctx.fillStyle = 'rgba(2,4,8,0.92)';
  ctx.fill();
  ctx.stroke();
  ctx.restore();

  const innerTop = headY + gapBelowHead;

  ctx.save();
  // Hard clip to the slab interior, so an over-long prompt truncates instead of bleeding out.
  ctx.beginPath();
  ctx.rect(r.x + b.W * 0.02, innerTop - px, r.w - b.W * 0.04, textH + px);
  ctx.clip();
  ctx.direction = rtl ? 'rtl' : 'ltr';
  ctx.textAlign = rtl ? 'right' : 'left';
  ctx.textBaseline = 'alphabetic';
  ctx.fillStyle = 'rgba(226,232,240,0.93)';
  const x = rtl ? r.x + r.w - b.W * 0.03 : r.x + b.W * 0.03;
  let y = innerTop + px;
  for (const line of lines) {
    if (y > innerTop + textH) break;
    ctx.fillText(line, x, y);
    y += px * 1.5;
  }
  ctx.restore();
}

function drawBulletList(ctx: CanvasRenderingContext2D, b: SlideBox, r: Region, bullets: string[], top: number, maxH: number, marker: 'check' | 'dot') {
  const items = bullets.slice(0, 5);
  if (!items.length) return;
  const rowH = Math.min(b.W * 0.16, maxH / items.length);
  let y = top;
  for (const raw of items) {
    const h = rowH - b.W * 0.014;
    glassPanel(ctx, r.x, y, r.w, h, b.W * 0.02);
    const boxS = b.W * 0.037;
    const bx = r.x + r.w - b.W * 0.032 - boxS;
    const by = y + h / 2 - boxS / 2;
    if (marker === 'check') {
      roundRectPath(ctx, bx, by, boxS, boxS, boxS * 0.25);
      ctx.fillStyle = hexToRgba(BRAND_GREEN, 0.16);
      ctx.fill();
      ctx.strokeStyle = BRAND_GREEN;
      ctx.lineWidth = 2;
      ctx.stroke();
      ctx.save();
      ctx.strokeStyle = BRAND_GREEN;
      ctx.lineWidth = boxS * 0.11;
      ctx.lineCap = 'round';
      ctx.beginPath();
      ctx.moveTo(bx + boxS * 0.26, by + boxS * 0.52);
      ctx.lineTo(bx + boxS * 0.45, by + boxS * 0.72);
      ctx.lineTo(bx + boxS * 0.76, by + boxS * 0.3);
      ctx.stroke();
      ctx.restore();
    } else {
      ctx.beginPath();
      ctx.arc(bx + boxS / 2, by + boxS / 2, boxS * 0.22, 0, Math.PI * 2);
      ctx.fillStyle = CYBER_CYAN;
      ctx.fill();
    }
    ctx.direction = 'rtl';
    ctx.textAlign = 'right';
    ctx.textBaseline = 'alphabetic';
    const { lines, px } = autoFit(ctx, sanitizeHebrewText(raw), r.w - boxS - b.W * 0.09, b.W * 0.03, b.W * 0.02, 2, (c, p) => setBody(c, p, 500));
    setBody(ctx, px, 500);
    ctx.fillStyle = 'rgba(255,255,255,0.95)';
    let ty = y + h / 2 - ((lines.length - 1) * px * 1.3) / 2 + px * 0.34;
    for (const line of lines) {
      ctx.fillText(line, bx - b.W * 0.022, ty);
      ty += px * 1.3;
    }
    y += rowH;
  }
}

/**
 * The UI path the thread told the reader to walk, as an LTR breadcrumb of chips.
 *
 * Menu labels are never translated — a reader following along needs the literal string printed in
 * the product — so the row is drawn left-to-right and right-aligned as a block into the RTL column,
 * which is where the eye lands first in Hebrew. Returns the y the next element may start at.
 */
function drawWorkflowPath(
  ctx: CanvasRenderingContext2D,
  b: SlideBox,
  r: Region,
  segs: string[],
  top: number,
  accent: string
): number {
  const steps = segs.map((s) => s.trim()).filter(Boolean).slice(0, 4);
  if (!steps.length) return top;

  const h = b.W * 0.05;
  const padX = b.W * 0.019;
  const gap = b.W * 0.028;
  let px = b.W * 0.02;
  const width = () => {
    setMono(ctx, px, 700);
    return steps.reduce((w, s) => w + ctx.measureText(s).width + padX * 2, 0) + gap * (steps.length - 1);
  };
  // Shrink rather than wrap: a path broken across two lines stops reading as one journey.
  let total = width();
  while (total > r.w && px > b.W * 0.012) {
    px *= 0.94;
    total = width();
  }

  ctx.save();
  ctx.direction = 'ltr';
  ctx.textAlign = 'left';
  ctx.textBaseline = 'middle';
  const midY = top + h / 2;
  let x = r.x + r.w - total;
  steps.forEach((step, i) => {
    const w = ctx.measureText(step).width + padX * 2;
    roundRectPath(ctx, x, top, w, h, h * 0.32);
    ctx.fillStyle = ZINC_900;
    ctx.fill();
    ctx.strokeStyle = ZINC_800;
    ctx.lineWidth = 1.5;
    ctx.stroke();
    ctx.fillStyle = 'rgba(226,232,240,0.95)';
    ctx.fillText(step, x + padX, midY + 1);
    x += w;
    if (i < steps.length - 1) {
      ctx.fillStyle = accent;
      ctx.textAlign = 'center';
      ctx.fillText('›', x + gap / 2, midY);
      ctx.textAlign = 'left';
      x += gap;
    }
  });
  ctx.restore();
  return top + h + b.W * 0.026;
}

function drawStepBadge(
  ctx: CanvasRenderingContext2D,
  b: SlideBox,
  r: Region,
  n: number,
  accent: string,
  ring = false
): number {
  const size = b.W * 0.115;
  const x = r.x + r.w - size;
  const y = r.y;
  ctx.save();
  roundRectPath(ctx, x, y, size, size, size * 0.28);
  ctx.fillStyle = hexToRgba(accent, 0.14);
  ctx.fill();
  ctx.strokeStyle = hexToRgba(accent, 0.55);
  ctx.lineWidth = 2;
  ctx.stroke();
  ctx.direction = 'ltr';
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';
  setDisplay(ctx, size * 0.52, 900);
  // Glow and numeral are drawn as separate passes: a shadowBlur applied to the fill itself
  // smeared the digit's own edges. The halo goes down first, then the numeral is painted crisp
  // with the shadow cleared, so the badge reads sharp at slide scale.
  ctx.fillStyle = accent;
  ctx.shadowColor = accent;
  ctx.shadowBlur = 16;
  ctx.globalAlpha = 0.55;
  ctx.fillText(String(n), x + size / 2, y + size / 2 + 2);
  ctx.shadowBlur = 0;
  ctx.globalAlpha = 1;
  ctx.fillText(String(n), x + size / 2, y + size / 2 + 2);
  ctx.restore();
  // The circled numeral — seeded off the step number so the same step is ringed identically in the
  // carousel PNG and in every frame of the reel.
  if (ring) {
    scribbleCircle(ctx, x + size / 2, y + size / 2, size * 0.74, size * 0.68, accent, n * 313 + 5);
  }
  return y + size + b.W * 0.03;
}

// ─── main painter ───────────────────────────────────────────────────────────────────────────

export interface SlideAnim {
  /** 0..1 entrance progress — drives the fade/rise of the slide's body content. */
  intro: number;
  /** 0..1 crossfade-out at the end of a scene (motion export only). */
  outro: number;
}

export function drawTipSlide(
  ctx: CanvasRenderingContext2D,
  b: SlideBox,
  slide: TechTipSlide,
  index: number,
  total: number,
  bg: HTMLImageElement | null,
  logo: HTMLImageElement | null,
  anim: SlideAnim = { intro: 1, outro: 0 }
) {
  ctx.clearRect(0, 0, b.W, b.H);
  const accent = accentFor(slide);
  // The backdrop is lit in the slide's own brand pair, so a photo-free technical slide still
  // carries the tool's identity before a single word is read.
  paintProceduralBackground(ctx, b, index, accent, glowFor(slide));
  if (bg) drawBackgroundImage(ctx, b, bg);
  drawTopBar(ctx, b, slide, index, total, logo, accent);
  drawBottomBar(ctx, b, index, total, accent);

  const r = contentRegion(b);
  const alpha = Math.max(0, Math.min(1, anim.intro)) * (1 - Math.max(0, Math.min(1, anim.outro)));
  const rise = (1 - Math.min(1, anim.intro)) * b.W * 0.02;

  ctx.save();
  ctx.globalAlpha = alpha;
  ctx.translate(0, rise);

  const region: Region = { ...r };
  let cursorY = region.y;

  if (slide.kind === 'step' && slide.stepNumber > 0) {
    cursorY = drawStepBadge(ctx, b, region, slide.stepNumber, accent, slide.scribble === 'circle');
    region.y = cursorY;
    region.h = r.y + r.h - cursorY;
  }

  if (slide.kind === 'cover' || slide.kind === 'cta') {
    // Centred, oversized title + supporting line.
    // Tool lockup above the headline — mark plus wordmark, centred. The cover of a creator deck
    // names its subject before the title does, which is what makes it identifiable in a grid.
    if (slide.kind === 'cover' && slide.tool) {
      const t = TOOL_STYLE[slide.tool];
      const ms = b.W * 0.072;
      const lockGap = b.W * 0.018;
      ctx.save();
      ctx.direction = 'ltr';
      ctx.textAlign = 'left';
      ctx.textBaseline = 'middle';
      setMono(ctx, b.W * 0.026, 700);
      const lockW = ms + lockGap + ctx.measureText(t.label).width;
      const lx = b.W / 2 - lockW / 2;
      const ly = region.y + region.h * 0.1;
      drawToolMark(ctx, slide.tool, lx, ly - ms / 2, ms, t.accent);
      ctx.fillStyle = 'rgba(226,232,240,0.92)';
      ctx.fillText(t.label, lx + ms + lockGap, ly + 1);
      ctx.restore();
    }

    const { lines, px } = autoFit(ctx, sanitizeHebrewText(slide.title), region.w, b.W * 0.085, b.W * 0.042, 5, (c, p) => setDisplay(c, p, 800));
    setDisplay(ctx, px, 800);
    ctx.direction = 'rtl';
    ctx.textAlign = 'center';
    ctx.textBaseline = 'alphabetic';
    let y = region.y + region.h * 0.3 - ((lines.length - 1) * px * 1.18) / 2;
    let lastBaseline = y;
    let lastWidth = 0;
    for (const line of lines) {
      const grad = ctx.createLinearGradient(region.x + region.w, 0, region.x, 0);
      grad.addColorStop(0, '#FFFFFF');
      grad.addColorStop(0.55, SILVER);
      grad.addColorStop(1, accent);
      ctx.fillStyle = grad;
      ctx.fillText(line, b.W / 2, y);
      lastBaseline = y;
      lastWidth = ctx.measureText(line).width;
      y += px * 1.18;
    }
    // Marker underline beneath the closing line of the headline — the one hand-drawn mark on a
    // cover. Measured off the line actually painted, so it tracks the auto-fitted type size.
    if (slide.scribble === 'underline' && lastWidth > 0) {
      const uw = Math.min(lastWidth, region.w * 0.9);
      scribbleUnderline(ctx, b.W / 2 - uw / 2, lastBaseline + px * 0.28, uw, accent, index * 977 + 13);
    }
    if (slide.body) {
      y += b.W * 0.03;
      setBody(ctx, b.W * 0.034, 400);
      ctx.fillStyle = 'rgba(226,232,240,0.85)';
      for (const line of wrapRtl(ctx, sanitizeHebrewText(slide.body), region.w * 0.9).slice(0, 5)) {
        ctx.fillText(line, b.W / 2, y);
        y += b.W * 0.048;
      }
    }
    if (slide.kind === 'cta') {
      y += b.W * 0.05;
      ctx.direction = 'ltr';
      // A Threads deck's CTA promotes the specific guide the agent matched to the topic; a deck
      // that names no target keeps the bare domain, which is what the Tech Tips CTA has always
      // drawn. A guide path is far longer than the domain, so the pill shrinks to fit the content
      // column instead of running off the slide edge.
      const target = (slide.ctaUrl ?? '').trim().replace(/^https?:\/\//i, '').replace(/\/$/, '');
      const label = `🔗  ${target || DOMAIN}`;
      let lp = b.W * 0.032;
      setDisplay(ctx, lp, 800);
      while (lp > b.W * 0.017 && ctx.measureText(label).width + b.W * 0.07 > region.w) {
        lp *= 0.94;
        setDisplay(ctx, lp, 800);
      }
      const tw = Math.min(region.w, ctx.measureText(label).width + b.W * 0.07);
      const ph = Math.max(b.W * 0.05, lp * 2.1);
      roundRectPath(ctx, b.W / 2 - tw / 2, y, tw, ph, ph / 2);
      ctx.save();
      ctx.shadowColor = accent;
      ctx.shadowBlur = 30;
      ctx.fillStyle = accent;
      ctx.fill();
      ctx.restore();
      ctx.fillStyle = '#05070A';
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      ctx.fillText(label, b.W / 2, y + ph / 2 + 1);
    }
  } else {
    let afterTitle = drawTitle(ctx, b, region, slide.title, b.W * 0.052, 3, accent) + b.W * 0.028;
    // The click-path sits directly beneath the title: it IS the slide's instruction, and the body,
    // prompt card or snippet below it are the elaboration.
    if (slide.workflowPath?.length) {
      afterTitle = drawWorkflowPath(ctx, b, region, slide.workflowPath, afterTitle, accent);
    }
    const remaining = region.y + region.h - afterTitle;

    if (slide.kind === 'code' && slide.code.trim()) {
      if (slide.body) {
        setBody(ctx, b.W * 0.028, 400);
        ctx.direction = 'rtl';
        ctx.textAlign = 'right';
        ctx.fillStyle = 'rgba(226,232,240,0.8)';
        let by = afterTitle;
        for (const line of wrapRtl(ctx, sanitizeHebrewText(slide.body), region.w).slice(0, 2)) {
          ctx.fillText(line, region.x + region.w, by);
          by += b.W * 0.04;
        }
        drawCodeBlock(ctx, b, region, slide, by + b.W * 0.015, region.y + region.h - (by + b.W * 0.015));
      } else {
        drawCodeBlock(ctx, b, region, slide, afterTitle, remaining);
      }
    } else if (slide.promptBox?.trim()) {
      // Same shape as the code branch: the body sets the prompt up in a line or two, the box is the
      // slide's actual payload. Checked after code so a slide carrying both never draws two panels.
      let boxTop = afterTitle;
      if (slide.body) {
        setBody(ctx, b.W * 0.028, 400);
        ctx.direction = 'rtl';
        ctx.textAlign = 'right';
        ctx.fillStyle = 'rgba(226,232,240,0.8)';
        let by = afterTitle;
        for (const line of wrapRtl(ctx, sanitizeHebrewText(slide.body), region.w).slice(0, 2)) {
          ctx.fillText(line, region.x + region.w, by);
          by += b.W * 0.04;
        }
        boxTop = by + b.W * 0.015;
      }
      // The doodle arrow gets its own reserved gap instead of being drawn over whatever sits
      // above the card. Room is taken from the card, so the arrow can never collide with the body
      // copy, and it is skipped outright when the card is already tight.
      const gap = slide.scribble === 'arrow' && region.y + region.h - boxTop > b.W * 0.55 ? b.W * 0.062 : 0;
      if (gap > 0) {
        doodleArrow(
          ctx,
          region.x + region.w * 0.27,
          boxTop + gap * 0.06,
          region.x + region.w * 0.15,
          boxTop + gap * 0.88,
          accent,
          index * 131 + 7
        );
      }
      drawPromptBox(ctx, b, region, slide.promptBox, boxTop + gap, region.y + region.h - boxTop - gap, accent);
    } else if ((slide.kind === 'tool' || slide.kind === 'takeaway') && slide.bullets.length) {
      drawBulletList(ctx, b, region, slide.bullets, afterTitle, remaining, slide.kind === 'takeaway' ? 'check' : 'dot');
    } else {
      drawParagraph(ctx, b, region, slide.body || slide.bullets.join('. '), afterTitle, remaining);
    }
  }

  ctx.restore();
}

// ─── still carousel export ──────────────────────────────────────────────────────────────────

async function ensureFonts() {
  await Promise.all([
    loadFont('800 90px Rubik'),
    loadFont('800 56px Rubik'),
    loadFont('400 40px Heebo'),
    loadFont('500 32px Heebo'),
    loadFont("500 28px 'JetBrains Mono'"),
    loadFont("700 20px 'JetBrains Mono'"),
  ]);
}

export async function renderTipDeckImages(
  deck: TechTipDeck,
  opts: { width?: number; height?: number; backgrounds?: (HTMLImageElement | null)[] } = {},
  onProgress?: (done: number, total: number) => void
): Promise<string[]> {
  const width = opts.width ?? 1080;
  const height = opts.height ?? 1350;
  const b = boxFor(width, height);
  const logo = await getLogo();
  await ensureFonts();

  const out: string[] = [];
  for (let i = 0; i < deck.slides.length; i++) {
    const canvas = document.createElement('canvas');
    canvas.width = width;
    canvas.height = height;
    const ctx = canvas.getContext('2d');
    if (!ctx) throw new Error('canvas 2d context unavailable');
    ctx.imageSmoothingEnabled = true;
    ctx.imageSmoothingQuality = 'high';
    drawTipSlide(ctx, b, deck.slides[i], i, deck.slides.length, opts.backgrounds?.[i] ?? null, logo);
    out.push(canvas.toDataURL('image/png'));
    onProgress?.(i + 1, deck.slides.length);
  }
  return out;
}

function dataUrlToBytes(dataUrl: string): Uint8Array {
  const base64 = dataUrl.split(',')[1] ?? '';
  const bin = atob(base64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return bytes;
}

export async function exportTipDeckZip(deck: TechTipDeck, images: string[], caption: string): Promise<void> {
  const zip = new JSZip();
  const slug = (deck.title || 'tech-tip').replace(/[^\w֐-׿]+/g, '-').slice(0, 40) || 'tech-tip';
  images.forEach((img, i) => {
    const s = deck.slides[i];
    if (img && s) zip.file(`${String(i + 1).padStart(2, '0')}_${s.kind}.png`, dataUrlToBytes(img));
  });
  zip.file('caption.txt', caption);
  zip.file(
    'code-snippets.txt',
    deck.slides
      .map((s, i) => (s.code.trim() ? `--- slide ${i + 1} (${s.codeLang}) — ${s.title}\n${s.code}\n` : ''))
      .filter(Boolean)
      .join('\n')
  );
  const blob = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `mrdaniel-tips-${slug}.zip`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
