import JSZip from 'jszip';
import { loadImage, getLogo, loadFont, wrapRtl, BRAND_GREEN } from './newsImageComposer';
import { sanitizeHebrewText } from './hebrewTextSanitizer';
import { highlightCode, TOKEN_PALETTE } from './syntaxHighlight';
import type { TechTipDeck, TechTipSlide, ThreadTheme } from './techTipsApi';
import { resolveSlidePhotoUrl, loadPhoto } from './pexelsBackground';

/**
 * Tech Tips slide painter — dark-cyber teaching slides, drawn on <canvas> so the SAME painter
 * feeds both outputs: the still carousel PNGs and every frame of the animated reel
 * (motionStudioService.ts). Size-agnostic: pass 1080×1350 for a 4:5 carousel or 1080×1920 for a
 * 9:16 reel and the layout scales off the canvas box rather than hard-coded coordinates.
 *
 * Backgrounds are OPTIONAL and generated by Pollinations (free, keyless, CORS-open — verified) from
 * each slide's own `visualPrompt`. Off by default: generation adds seconds per slide, and every
 * slide already reads correctly on the procedural obsidian+grid backdrop, which is the fallback
 * whenever generation is disabled, slow, or fails.
 */

const OBSIDIAN_TOP = '#06080D';
const OBSIDIAN_BOTTOM = '#0B0F17';
const CYBER_CYAN = '#22D3EE';
const SILVER = '#E2E8F0';
const DOMAIN = 'mrdaniel.co.il';

/**
 * Accent per subject family, assigned by the Threads agent.
 *
 * A deck about Gemini and a deck about ransomware used to render in the identical cyan, so a
 * follower's feed showed one indistinguishable wall of slides. The accent drives the title
 * gradient, the badge and kicker chips, the step badge and the progress rail, which is enough to
 * tell two decks apart at thumbnail size without touching the layout. Every colour here clears
 * 4.5:1 against the obsidian backdrop.
 *
 * A deck that sets no theme (every Tech Tips deck) resolves to 'general' and renders exactly as it
 * did before this table existed.
 */
const THEME_ACCENT: Record<ThreadTheme, string> = {
  ai: CYBER_CYAN,
  automation: BRAND_GREEN,
  security: '#FB923C',
  code: '#A78BFA',
  data: '#38BDF8',
  web3: '#F0ABFC',
  general: BRAND_GREEN,
};

function accentFor(slide: TechTipSlide): string {
  return THEME_ACCENT[slide.theme ?? 'general'] ?? BRAND_GREEN;
}

export interface SlideBox {
  W: number;
  H: number;
  PAD: number;
}

export function boxFor(width: number, height: number): SlideBox {
  return { W: width, H: height, PAD: Math.round(width * 0.085) };
}

// ─── background ─────────────────────────────────────────────────────────────────────────────

function hexToRgba(hex: string, a: number): string {
  const n = parseInt(hex.replace('#', ''), 16);
  return `rgba(${(n >> 16) & 255},${(n >> 8) & 255},${n & 255},${a})`;
}

function paintProceduralBackground(ctx: CanvasRenderingContext2D, b: SlideBox, seed: number) {
  const g = ctx.createLinearGradient(0, 0, b.W * 0.4, b.H);
  g.addColorStop(0, OBSIDIAN_TOP);
  g.addColorStop(1, OBSIDIAN_BOTTOM);
  ctx.fillStyle = g;
  ctx.fillRect(0, 0, b.W, b.H);

  // carbon grid
  ctx.save();
  ctx.strokeStyle = 'rgba(226,232,240,0.035)';
  ctx.lineWidth = 1;
  const step = Math.round(b.W / 10);
  for (let x = step; x < b.W; x += step) {
    ctx.beginPath();
    ctx.moveTo(x + 0.5, 0);
    ctx.lineTo(x + 0.5, b.H);
    ctx.stroke();
  }
  for (let y = step; y < b.H; y += step) {
    ctx.beginPath();
    ctx.moveTo(0, y + 0.5);
    ctx.lineTo(b.W, y + 0.5);
    ctx.stroke();
  }
  ctx.restore();

  // ambient accent glow, seeded so consecutive slides differ
  const cx = b.W * (0.3 + ((seed * 37) % 40) / 100);
  const cy = b.H * (0.25 + ((seed * 53) % 45) / 100);
  const rg = ctx.createRadialGradient(cx, cy, 0, cx, cy, b.W * 0.75);
  rg.addColorStop(0, hexToRgba(seed % 2 === 0 ? BRAND_GREEN : CYBER_CYAN, 0.14));
  rg.addColorStop(1, 'rgba(0,0,0,0)');
  ctx.fillStyle = rg;
  ctx.fillRect(0, 0, b.W, b.H);
}

/** Pollinations: free + keyless + `Access-Control-Allow-Origin: *` (verified), so the generated
 * image can be drawn to canvas without tainting it. */
export function pollinationsUrl(prompt: string, width: number, height: number, seed: number): string {
  const p = encodeURIComponent(prompt.slice(0, 380));
  return `https://image.pollinations.ai/prompt/${p}?width=${width}&height=${height}&nologo=true&seed=${seed}`;
}

/** Resolves one AI backdrop per slide. Bounded concurrency + per-image timeout; any failure just
 * yields null and the slide falls back to the procedural backdrop. */
/**
 * Technologies whose logos meaningfully sharpen an illustration.
 *
 * A generic "abstract tech grid" backdrop is interchangeable between guides. Naming the actual
 * stack in the image prompt — the Python emblem, the Docker whale — anchors the illustration to
 * the subject and makes the set read as one deliberate series rather than stock filler.
 * Matched case-insensitively on word boundaries so "Go" does not fire on "Google".
 */
const BRAND_TERMS: { re: RegExp; visual: string }[] = [
  { re: /\bpython\b/i, visual: 'Python logo emblem, blue and yellow entwined serpents' },
  { re: /\bdocker\b/i, visual: 'Docker whale logo carrying shipping containers' },
  { re: /\b(kubernetes|k8s)\b/i, visual: 'Kubernetes blue helm wheel logo' },
  { re: /\breact\b/i, visual: 'React atom orbital logo in cyan' },
  { re: /\bnode(\.js)?\b/i, visual: 'Node.js green hexagon logo' },
  { re: /\b(typescript|ts)\b/i, visual: 'TypeScript blue square TS logo' },
  { re: /\bpostgres(ql)?\b/i, visual: 'PostgreSQL blue elephant logo' },
  { re: /\bmongo(db)?\b/i, visual: 'MongoDB green leaf logo' },
  { re: /\bredis\b/i, visual: 'Redis red stacked cubes logo' },
  { re: /\b(aws|amazon web services)\b/i, visual: 'AWS orange logo above a cloud datacenter' },
  { re: /\bazure\b/i, visual: 'Microsoft Azure blue triangle logo' },
  { re: /\bgit(hub)?\b/i, visual: 'GitHub Octocat logo with branching version control graph' },
  { re: /\b(linux|ubuntu)\b/i, visual: 'Linux Tux penguin logo beside a terminal' },
  { re: /\bnginx\b/i, visual: 'NGINX green N logo' },
  { re: /\b(tensorflow|pytorch)\b/i, visual: 'machine learning framework logo over a neural network' },
  { re: /\b(openai|gpt)\b/i, visual: 'OpenAI hexagonal knot emblem' },
  { re: /\bfigma\b/i, visual: 'Figma multicoloured shapes logo' },
  { re: /\bterraform\b/i, visual: 'Terraform purple T logo, infrastructure as code' },
];

/** Brand/tech visuals named anywhere in the slide's own text. */
function brandVisualsFor(text: string): string[] {
  return BRAND_TERMS.filter((t) => t.re.test(text)).map((t) => t.visual).slice(0, 3);
}

/** Background sources offered in the Tips & Guides control bar. */
export type TipStyle = 'photoreal' | 'enterprise' | 'dark-minimal' | 'sketchnote';

/** Extra search terms per style, appended to the slide's own contextual query. */
const STYLE_TONE: Record<TipStyle, string> = {
  photoreal: 'professional photography',
  enterprise: 'bright clean corporate office technology',
  'dark-minimal': 'dark moody minimal technology',
  sketchnote: '',
};

export async function resolveTipBackgrounds(
  deck: TechTipDeck,
  width: number,
  height: number,
  onProgress?: (done: number, total: number) => void,
  style: TipStyle = 'photoreal'
): Promise<(HTMLImageElement | null)[]> {
  const total = deck.slides.length;
  const out: (HTMLImageElement | null)[] = new Array(total).fill(null);
  let done = 0;
  let cursor = 0;
  // Tracks fallback photos already used so two slides never land on the same stock image.
  const usedFallbacks = new Set<number>();
  const workers = Array.from({ length: Math.min(3, total) }, async () => {
    while (cursor < total) {
      const i = cursor++;
      const slide = deck.slides[i];
      if (slide.sourceImage) {
        // An image the thread itself published beats anything generated or searched: it is what the
        // post actually showed, so it can't be off-topic. Already routed through the site's own
        // relay by the fetcher, so it draws to canvas without tainting it. A failure yields null
        // and the slide falls back to the procedural backdrop, same as every other source here.
        out[i] = await loadPhoto(slide.sourceImage, 12000);
      } else if (style === 'sketchnote') {
        // Illustrated art: keep the existing Pollinations path driven by the slide's visualPrompt.
        const subject = [slide.title, slide.body, slide.code].filter(Boolean).join(' ');
        const brands = brandVisualsFor(subject);
        const prompt = [
          slide.visualPrompt || 'dark cyber technology scene, neon green accents',
          ...brands,
          // Pushes the model off generic wallpaper and towards a deliberate, readable illustration.
          'bold high-contrast digital illustration, dramatic rim lighting, deep dark background,',
          'sharp focal subject, cinematic depth, no text, no letters, no watermark',
        ].join(', ');
        out[i] = await Promise.race([
          loadImage(pollinationsUrl(prompt, Math.round(width / 2), Math.round(height / 2), i + 7)),
          new Promise<null>((r) => setTimeout(() => r(null), 30000)),
        ]);
      } else {
        // Photographic styles: build the query from THIS slide's own text, not the deck title, so
        // each slide gets its own matched image. resolveSlidePhotoUrl sends the slide text to the
        // server, which derives a targeted English scene query for it.
        const slideText = [slide.title, slide.body, slide.visualPrompt]
          .filter(Boolean).join(' ').slice(0, 320);
        const orientation = height > width ? 'portrait' : height === width ? 'square' : 'landscape';
        const url = await resolveSlidePhotoUrl(
          `${slideText} ${STYLE_TONE[style]}`.trim(),
          deck.title || slide.title || 'technology',
          orientation,
          i + 7,
          usedFallbacks
        );
        out[i] = await Promise.race([
          loadPhoto(url, 12000),
          new Promise<null>((r) => setTimeout(() => r(null), 15000)),
        ]);
      }
      done++;
      onProgress?.(done, total);
    }
  });
  await Promise.all(workers);
  return out;
}

function drawBackgroundImage(ctx: CanvasRenderingContext2D, b: SlideBox, img: HTMLImageElement) {
  const iw = img.naturalWidth;
  const ih = img.naturalHeight;
  if (!iw || !ih) return;
  const canvasRatio = b.W / b.H;
  const imgRatio = iw / ih;
  let sw: number, sh: number, sx: number, sy: number;
  if (imgRatio > canvasRatio) {
    sh = ih;
    sw = sh * canvasRatio;
    sx = (iw - sw) / 2;
    sy = 0;
  } else {
    sw = iw;
    sh = sw / canvasRatio;
    sx = 0;
    sy = (ih - sh) / 2;
  }
  ctx.drawImage(img, sx, sy, sw, sh, 0, 0, b.W, b.H);
  // Heavy scrim: the AI backdrop is texture, never competition for the teaching content.
  ctx.fillStyle = 'rgba(6,8,13,0.78)';
  ctx.fillRect(0, 0, b.W, b.H);
}

// ─── chrome ─────────────────────────────────────────────────────────────────────────────────

function roundRectPath(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, r: number) {
  const rr = Math.max(0, Math.min(r, w / 2, h / 2));
  ctx.beginPath();
  ctx.moveTo(x + rr, y);
  ctx.arcTo(x + w, y, x + w, y + h, rr);
  ctx.arcTo(x + w, y + h, x, y + h, rr);
  ctx.arcTo(x, y + h, x, y, rr);
  ctx.arcTo(x, y, x + w, y, rr);
  ctx.closePath();
}

function glassPanel(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, r: number, accent?: string) {
  ctx.save();
  ctx.shadowColor = 'rgba(0,0,0,0.5)';
  ctx.shadowBlur = 36;
  ctx.shadowOffsetY = 18;
  roundRectPath(ctx, x, y, w, h, r);
  ctx.fillStyle = 'rgba(255,255,255,0.035)';
  ctx.fill();
  ctx.restore();
  roundRectPath(ctx, x, y, w, h, r);
  ctx.strokeStyle = accent ? hexToRgba(accent, 0.35) : 'rgba(255,255,255,0.10)';
  ctx.lineWidth = 1.5;
  ctx.stroke();
}

const setDisplay = (ctx: CanvasRenderingContext2D, px: number, w = 800) => {
  ctx.font = `${w} ${Math.round(px)}px Rubik, Heebo, sans-serif`;
};
const setBody = (ctx: CanvasRenderingContext2D, px: number, w = 400) => {
  ctx.font = `${w} ${Math.round(px)}px Heebo, Rubik, sans-serif`;
};
const setMono = (ctx: CanvasRenderingContext2D, px: number, w = 500) => {
  ctx.font = `${w} ${Math.round(px)}px 'JetBrains Mono', 'Heebo', monospace`;
};

function autoFit(
  ctx: CanvasRenderingContext2D,
  text: string,
  maxW: number,
  startPx: number,
  minPx: number,
  maxLines: number,
  set: (c: CanvasRenderingContext2D, px: number) => void
): { lines: string[]; px: number } {
  let px = startPx;
  let lines: string[] = [];
  for (let i = 0; i < 24; i++) {
    set(ctx, px);
    lines = wrapRtl(ctx, text, maxW);
    if (lines.length <= maxLines || px <= minPx) break;
    px = Math.max(minPx, px * 0.93);
  }
  return { lines, px };
}

function drawTopBar(
  ctx: CanvasRenderingContext2D,
  b: SlideBox,
  slide: TechTipSlide,
  index: number,
  total: number,
  logo: HTMLImageElement | null,
  accent: string
) {
  const y = Math.round(b.H * 0.045);
  // Progress, left (LTR). A Threads deck counts the SUB-POSTS it was built from ("2 / 7"), which is
  // the sequence the reader is actually stepping through; a deck with no sub-posts keeps the
  // deck-wide slide index it always showed.
  const progress =
    slide.stepLabel?.trim() || `${String(index + 1).padStart(2, '0')} / ${String(total).padStart(2, '0')}`;
  ctx.save();
  ctx.direction = 'ltr';
  ctx.textAlign = 'left';
  ctx.textBaseline = 'middle';
  setMono(ctx, b.W * 0.019, 600);
  ctx.fillStyle = 'rgba(226,232,240,0.55)';
  ctx.fillText(progress, b.PAD, y);
  const progressW = ctx.measureText(progress).width;
  ctx.restore();

  // Topic badge, beside the counter. Latin by design — "Gemini AI", not a transliteration — so it
  // is drawn LTR next to the LTR counter rather than in the RTL lane on the right.
  const badge = (slide.badge ?? '').trim();
  if (badge) {
    ctx.save();
    ctx.direction = 'ltr';
    ctx.textAlign = 'left';
    ctx.textBaseline = 'middle';
    setMono(ctx, b.W * 0.0165, 700);
    const bw = ctx.measureText(badge).width + b.W * 0.03;
    const bh = b.W * 0.034;
    const bx = b.PAD + progressW + b.W * 0.022;
    roundRectPath(ctx, bx, y - bh / 2, bw, bh, bh * 0.3);
    ctx.fillStyle = hexToRgba(accent, 0.14);
    ctx.fill();
    ctx.strokeStyle = hexToRgba(accent, 0.5);
    ctx.lineWidth = 1;
    ctx.stroke();
    ctx.fillStyle = accent;
    ctx.fillText(badge, bx + b.W * 0.015, y + 1);
    ctx.restore();
  }

  // kicker chip, right (RTL)
  const kicker = sanitizeHebrewText(slide.kicker || '');
  if (kicker) {
    ctx.save();
    ctx.direction = 'rtl';
    ctx.textAlign = 'right';
    ctx.textBaseline = 'middle';
    setMono(ctx, b.W * 0.018, 600);
    const kw = ctx.measureText(kicker).width + b.W * 0.035;
    const kh = b.W * 0.038;
    const kx = b.W - b.PAD - kw;
    roundRectPath(ctx, kx, y - kh / 2, kw, kh, kh * 0.28);
    ctx.fillStyle = hexToRgba(accent, 0.12);
    ctx.fill();
    ctx.strokeStyle = hexToRgba(accent, 0.45);
    ctx.lineWidth = 1;
    ctx.stroke();
    ctx.fillStyle = accent;
    ctx.fillText(kicker, b.W - b.PAD - b.W * 0.017, y + 1);
    ctx.restore();
  }

  if (logo) {
    const h = b.W * 0.032;
    const w = h * (logo.naturalWidth / logo.naturalHeight || 3);
    ctx.save();
    ctx.globalAlpha = 0.85;
    ctx.drawImage(logo, b.W / 2 - w / 2, y - h / 2, w, h);
    ctx.restore();
  }
}

function drawBottomBar(ctx: CanvasRenderingContext2D, b: SlideBox, index: number, total: number, accent: string) {
  const railY = b.H - b.PAD * 1.15;
  const gap = 7;
  const railW = b.W - b.PAD * 2;
  const segW = (railW - gap * (total - 1)) / total;
  for (let i = 0; i < total; i++) {
    const x = b.PAD + i * (segW + gap);
    roundRectPath(ctx, x, railY, Math.max(2, segW), 5, 2.5);
    ctx.fillStyle = i <= index ? accent : 'rgba(255,255,255,0.14)';
    ctx.fill();
  }
  ctx.save();
  ctx.direction = 'ltr';
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';
  setMono(ctx, b.W * 0.019, 600);
  ctx.fillStyle = 'rgba(226,232,240,0.6)';
  ctx.fillText(DOMAIN, b.W / 2, b.H - b.PAD * 0.5);
  ctx.restore();
}

// ─── per-kind bodies ────────────────────────────────────────────────────────────────────────

interface Region {
  x: number;
  y: number;
  w: number;
  h: number;
}

function contentRegion(b: SlideBox): Region {
  const top = b.H * 0.14;
  const bottom = b.H - b.PAD * 1.9;
  return { x: b.PAD, y: top, w: b.W - b.PAD * 2, h: bottom - top };
}

function drawTitle(ctx: CanvasRenderingContext2D, b: SlideBox, r: Region, title: string, startPx: number, maxLines: number, accent: string): number {
  if (!title) return r.y;
  const { lines, px } = autoFit(ctx, sanitizeHebrewText(title), r.w, startPx, b.W * 0.032, maxLines, (c, p) => setDisplay(c, p, 800));
  setDisplay(ctx, px, 800);
  ctx.direction = 'rtl';
  ctx.textAlign = 'right';
  ctx.textBaseline = 'alphabetic';
  let y = r.y + px;
  for (const line of lines) {
    const grad = ctx.createLinearGradient(r.x + r.w, 0, r.x, 0);
    grad.addColorStop(0, '#FFFFFF');
    grad.addColorStop(0.6, SILVER);
    grad.addColorStop(1, accent);
    ctx.fillStyle = grad;
    ctx.fillText(line, r.x + r.w, y);
    y += px * 1.18;
  }
  return y;
}

function drawParagraph(ctx: CanvasRenderingContext2D, b: SlideBox, r: Region, text: string, top: number, maxH: number) {
  if (!text) return;
  const { lines, px } = autoFit(ctx, sanitizeHebrewText(text), r.w - b.W * 0.06, b.W * 0.038, b.W * 0.022, 14, (c, p) => setBody(c, p, 400));
  const lh = px * 1.55;
  const panelH = Math.min(maxH, lines.length * lh + b.W * 0.075);
  glassPanel(ctx, r.x, top, r.w, panelH, b.W * 0.028);
  setBody(ctx, px, 400);
  ctx.fillStyle = 'rgba(255,255,255,0.94)';
  ctx.direction = 'rtl';
  ctx.textAlign = 'right';
  let y = top + b.W * 0.045 + px;
  for (const line of lines) {
    if (y > top + panelH - b.W * 0.01) break;
    ctx.fillText(line, r.x + r.w - b.W * 0.03, y);
    y += lh;
  }
}

function drawCodeBlock(ctx: CanvasRenderingContext2D, b: SlideBox, r: Region, slide: TechTipSlide, top: number, maxH: number) {
  const lines = highlightCode(slide.code, slide.codeLang);
  const panelH = maxH;
  glassPanel(ctx, r.x, top, r.w, panelH, b.W * 0.024, CYBER_CYAN);

  // window chrome + language tag
  ctx.save();
  for (let i = 0; i < 3; i++) {
    ctx.beginPath();
    ctx.arc(r.x + b.W * 0.032 + i * b.W * 0.022, top + b.W * 0.032, b.W * 0.0055, 0, Math.PI * 2);
    ctx.fillStyle = ['#F87171', '#FBBF24', '#34D399'][i];
    ctx.fill();
  }
  ctx.direction = 'ltr';
  ctx.textAlign = 'right';
  ctx.textBaseline = 'middle';
  setMono(ctx, b.W * 0.017, 700);
  ctx.fillStyle = hexToRgba(CYBER_CYAN, 0.85);
  ctx.fillText((slide.codeLang || 'code').toUpperCase(), r.x + r.w - b.W * 0.028, top + b.W * 0.032);
  ctx.restore();

  // Fit the snippet. Shrinking alone was not enough: once the floor size was reached a long line
  // simply kept overflowing the terminal border (the slide-03 bug), because nothing ever wrapped.
  // Now the width budget is enforced by WRAPPING at the token level after shrinking, and the panel
  // is clipped as a final guarantee that no glyph can paint outside the box.
  const innerTop = top + b.W * 0.062;
  const innerH = panelH - b.W * 0.078;
  const innerX = r.x + b.W * 0.028;
  const innerW = r.w - b.W * 0.075;

  let px = b.W * 0.026;
  const minPx = b.W * 0.0135;
  let wrapped: { toks: { text: string; color: keyof typeof TOKEN_PALETTE }[]; num: number | null }[] = [];

  for (let i = 0; i < 24; i++) {
    setMono(ctx, px, 500);
    const gutter = px * 2.2;
    const textW = innerW - gutter;
    wrapped = wrapCodeLines(ctx, lines, textW);
    if ((wrapped.length * px * 1.5 <= innerH && maxTokenWidth(ctx, wrapped) <= textW) || px <= minPx) break;
    px = Math.max(minPx, px * 0.94);
  }
  setMono(ctx, px, 500);
  const lh = px * 1.5;
  const gutterW = px * 2.2;

  ctx.save();
  // Hard clip to the panel interior — belt and braces against any residual overflow.
  ctx.beginPath();
  ctx.rect(innerX - px * 0.3, innerTop - px, innerW + px * 0.6, innerH + px);
  ctx.clip();
  ctx.direction = 'ltr';
  ctx.textAlign = 'left';
  ctx.textBaseline = 'alphabetic';
  let y = innerTop + px;
  for (const row of wrapped) {
    if (y > innerTop + innerH) break;
    if (row.num !== null) {
      ctx.fillStyle = 'rgba(148,163,184,0.35)';
      ctx.fillText(String(row.num).padStart(2, ' '), innerX, y);
    }
    // Continuation rows indent slightly so a wrapped line reads as one statement.
    let x = innerX + gutterW + (row.num === null ? px * 1.2 : 0);
    for (const tok of row.toks) {
      ctx.fillStyle = TOKEN_PALETTE[tok.color];
      ctx.fillText(tok.text, x, y);
      x += ctx.measureText(tok.text).width;
    }
    y += lh;
  }
  ctx.restore();
}

/** Widest rendered row, used by the fit loop. */
function maxTokenWidth(
  ctx: CanvasRenderingContext2D,
  rows: { toks: { text: string; color: keyof typeof TOKEN_PALETTE }[] }[]
): number {
  return rows.reduce(
    (m, row) => Math.max(m, ctx.measureText(row.toks.map((t) => t.text).join('')).width),
    0
  );
}

/**
 * Wraps highlighted code lines to a pixel width, preserving token colours.
 *
 * Splits on token boundaries first and only breaks inside a token when a single token is itself
 * wider than the budget (a long URL or path), so syntax colouring survives the wrap. Continuation
 * rows carry `num: null` so the line-number gutter is not repeated.
 */
function wrapCodeLines(
  ctx: CanvasRenderingContext2D,
  lines: { text: string; color: keyof typeof TOKEN_PALETTE }[][],
  maxW: number
): { toks: { text: string; color: keyof typeof TOKEN_PALETTE }[]; num: number | null }[] {
  const out: { toks: { text: string; color: keyof typeof TOKEN_PALETTE }[]; num: number | null }[] = [];
  if (maxW <= 0) return out;

  lines.forEach((toks, idx) => {
    let row: { text: string; color: keyof typeof TOKEN_PALETTE }[] = [];
    let rowW = 0;
    let first = true;
    const push = () => {
      out.push({ toks: row, num: first ? idx + 1 : null });
      first = false;
      row = [];
      rowW = 0;
    };

    for (const tok of toks) {
      let text = tok.text;
      while (text) {
        const w = ctx.measureText(text).width;
        if (rowW + w <= maxW) {
          row.push({ text, color: tok.color });
          rowW += w;
          break;
        }
        // Find how much of this token still fits on the current row.
        let fit = text.length;
        while (fit > 0 && rowW + ctx.measureText(text.slice(0, fit)).width > maxW) fit--;
        if (fit === 0) {
          if (row.length === 0) fit = 1; // pathological: force at least one char to avoid a stall
          else {
            push();
            continue;
          }
        }
        row.push({ text: text.slice(0, fit), color: tok.color });
        text = text.slice(fit);
        push();
      }
    }
    if (row.length > 0 || first) push();
  });

  return out;
}

/**
 * Plain greedy word wrap for Latin text. `wrapRtl` is tuned for Hebrew shaping; a quoted prompt is
 * usually English and only needs word breaking, with blank lines preserved as paragraph breaks.
 */
function wrapLtr(ctx: CanvasRenderingContext2D, text: string, maxW: number): string[] {
  const out: string[] = [];
  for (const para of text.split('\n')) {
    let line = '';
    for (const word of para.split(/\s+/).filter(Boolean)) {
      const next = line ? `${line} ${word}` : word;
      if (!line || ctx.measureText(next).width <= maxW) {
        line = next;
      } else {
        out.push(line);
        line = word;
      }
    }
    out.push(line);
  }
  return out;
}

/**
 * A prompt lifted from the source thread, in its own dark copyable container.
 *
 * Deliberately not drawCodeBlock: a prompt is text to COPY into a model, not source to read, so it
 * gets a plain slab with a copy affordance and no line numbers or syntax colouring — tokenising
 * English prose as if it were code makes it harder to read, not easier. Direction follows the
 * prompt's own script, so a Hebrew prompt is not painted left-to-right.
 */
function drawPromptBox(
  ctx: CanvasRenderingContext2D,
  b: SlideBox,
  r: Region,
  raw: string,
  top: number,
  maxH: number,
  accent: string
) {
  const clean = raw.trim();
  if (!clean || maxH <= 0) return;
  const rtl = /[֐-׿]/.test(clean.slice(0, 80));

  ctx.save();
  roundRectPath(ctx, r.x, top, r.w, maxH, b.W * 0.024);
  ctx.fillStyle = 'rgba(2,4,8,0.74)';
  ctx.fill();
  roundRectPath(ctx, r.x, top, r.w, maxH, b.W * 0.024);
  ctx.strokeStyle = hexToRgba(accent, 0.45);
  ctx.lineWidth = 1.5;
  ctx.stroke();
  ctx.restore();

  // header: the PROMPT tag, plus the two-offset-squares mark that reads universally as "copy"
  const headY = top + b.W * 0.034;
  ctx.save();
  ctx.direction = 'ltr';
  ctx.textBaseline = 'middle';
  ctx.textAlign = 'left';
  setMono(ctx, b.W * 0.017, 700);
  ctx.fillStyle = hexToRgba(accent, 0.9);
  ctx.fillText('PROMPT', r.x + b.W * 0.03, headY);
  const gs = b.W * 0.022;
  const gx = r.x + r.w - b.W * 0.03 - gs;
  ctx.strokeStyle = hexToRgba(accent, 0.6);
  ctx.lineWidth = Math.max(1.4, b.W * 0.002);
  roundRectPath(ctx, gx + gs * 0.28, headY - gs * 0.64, gs * 0.72, gs * 0.72, gs * 0.16);
  ctx.stroke();
  roundRectPath(ctx, gx, headY - gs * 0.26, gs * 0.72, gs * 0.72, gs * 0.16);
  ctx.fillStyle = 'rgba(2,4,8,0.92)';
  ctx.fill();
  ctx.stroke();
  ctx.restore();

  const innerTop = headY + b.W * 0.032;
  const innerH = top + maxH - innerTop - b.W * 0.026;
  const innerW = r.w - b.W * 0.06;
  if (innerH <= 0) return;

  let px = b.W * 0.026;
  const minPx = b.W * 0.015;
  let lines: string[] = [];
  for (let i = 0; i < 24; i++) {
    setMono(ctx, px, 400);
    lines = rtl ? wrapRtl(ctx, sanitizeHebrewText(clean), innerW) : wrapLtr(ctx, clean, innerW);
    if (lines.length * px * 1.5 <= innerH || px <= minPx) break;
    px = Math.max(minPx, px * 0.94);
  }
  setMono(ctx, px, 400);

  ctx.save();
  // Hard clip to the slab interior, so an over-long prompt truncates instead of bleeding out.
  ctx.beginPath();
  ctx.rect(r.x + b.W * 0.02, innerTop - px, r.w - b.W * 0.04, innerH + px);
  ctx.clip();
  ctx.direction = rtl ? 'rtl' : 'ltr';
  ctx.textAlign = rtl ? 'right' : 'left';
  ctx.textBaseline = 'alphabetic';
  ctx.fillStyle = 'rgba(226,232,240,0.93)';
  const x = rtl ? r.x + r.w - b.W * 0.03 : r.x + b.W * 0.03;
  let y = innerTop + px;
  for (const line of lines) {
    if (y > innerTop + innerH) break;
    ctx.fillText(line, x, y);
    y += px * 1.5;
  }
  ctx.restore();
}

function drawBulletList(ctx: CanvasRenderingContext2D, b: SlideBox, r: Region, bullets: string[], top: number, maxH: number, marker: 'check' | 'dot') {
  const items = bullets.slice(0, 5);
  if (!items.length) return;
  const rowH = Math.min(b.W * 0.16, maxH / items.length);
  let y = top;
  for (const raw of items) {
    const h = rowH - b.W * 0.014;
    glassPanel(ctx, r.x, y, r.w, h, b.W * 0.02);
    const boxS = b.W * 0.037;
    const bx = r.x + r.w - b.W * 0.032 - boxS;
    const by = y + h / 2 - boxS / 2;
    if (marker === 'check') {
      roundRectPath(ctx, bx, by, boxS, boxS, boxS * 0.25);
      ctx.fillStyle = hexToRgba(BRAND_GREEN, 0.16);
      ctx.fill();
      ctx.strokeStyle = BRAND_GREEN;
      ctx.lineWidth = 2;
      ctx.stroke();
      ctx.save();
      ctx.strokeStyle = BRAND_GREEN;
      ctx.lineWidth = boxS * 0.11;
      ctx.lineCap = 'round';
      ctx.beginPath();
      ctx.moveTo(bx + boxS * 0.26, by + boxS * 0.52);
      ctx.lineTo(bx + boxS * 0.45, by + boxS * 0.72);
      ctx.lineTo(bx + boxS * 0.76, by + boxS * 0.3);
      ctx.stroke();
      ctx.restore();
    } else {
      ctx.beginPath();
      ctx.arc(bx + boxS / 2, by + boxS / 2, boxS * 0.22, 0, Math.PI * 2);
      ctx.fillStyle = CYBER_CYAN;
      ctx.fill();
    }
    ctx.direction = 'rtl';
    ctx.textAlign = 'right';
    ctx.textBaseline = 'alphabetic';
    const { lines, px } = autoFit(ctx, sanitizeHebrewText(raw), r.w - boxS - b.W * 0.09, b.W * 0.03, b.W * 0.02, 2, (c, p) => setBody(c, p, 500));
    setBody(ctx, px, 500);
    ctx.fillStyle = 'rgba(255,255,255,0.95)';
    let ty = y + h / 2 - ((lines.length - 1) * px * 1.3) / 2 + px * 0.34;
    for (const line of lines) {
      ctx.fillText(line, bx - b.W * 0.022, ty);
      ty += px * 1.3;
    }
    y += rowH;
  }
}

function drawStepBadge(ctx: CanvasRenderingContext2D, b: SlideBox, r: Region, n: number, accent: string): number {
  const size = b.W * 0.115;
  const x = r.x + r.w - size;
  const y = r.y;
  ctx.save();
  roundRectPath(ctx, x, y, size, size, size * 0.28);
  ctx.fillStyle = hexToRgba(accent, 0.14);
  ctx.fill();
  ctx.strokeStyle = hexToRgba(accent, 0.55);
  ctx.lineWidth = 2;
  ctx.stroke();
  ctx.direction = 'ltr';
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';
  setDisplay(ctx, size * 0.52, 900);
  // Glow and numeral are drawn as separate passes: a shadowBlur applied to the fill itself
  // smeared the digit's own edges. The halo goes down first, then the numeral is painted crisp
  // with the shadow cleared, so the badge reads sharp at slide scale.
  ctx.fillStyle = accent;
  ctx.shadowColor = accent;
  ctx.shadowBlur = 16;
  ctx.globalAlpha = 0.55;
  ctx.fillText(String(n), x + size / 2, y + size / 2 + 2);
  ctx.shadowBlur = 0;
  ctx.globalAlpha = 1;
  ctx.fillText(String(n), x + size / 2, y + size / 2 + 2);
  ctx.restore();
  return y + size + b.W * 0.03;
}

// ─── main painter ───────────────────────────────────────────────────────────────────────────

export interface SlideAnim {
  /** 0..1 entrance progress — drives the fade/rise of the slide's body content. */
  intro: number;
  /** 0..1 crossfade-out at the end of a scene (motion export only). */
  outro: number;
}

export function drawTipSlide(
  ctx: CanvasRenderingContext2D,
  b: SlideBox,
  slide: TechTipSlide,
  index: number,
  total: number,
  bg: HTMLImageElement | null,
  logo: HTMLImageElement | null,
  anim: SlideAnim = { intro: 1, outro: 0 }
) {
  ctx.clearRect(0, 0, b.W, b.H);
  paintProceduralBackground(ctx, b, index);
  if (bg) drawBackgroundImage(ctx, b, bg);

  const accent = accentFor(slide);
  drawTopBar(ctx, b, slide, index, total, logo, accent);
  drawBottomBar(ctx, b, index, total, accent);

  const r = contentRegion(b);
  const alpha = Math.max(0, Math.min(1, anim.intro)) * (1 - Math.max(0, Math.min(1, anim.outro)));
  const rise = (1 - Math.min(1, anim.intro)) * b.W * 0.02;

  ctx.save();
  ctx.globalAlpha = alpha;
  ctx.translate(0, rise);

  const region: Region = { ...r };
  let cursorY = region.y;

  if (slide.kind === 'step' && slide.stepNumber > 0) {
    cursorY = drawStepBadge(ctx, b, region, slide.stepNumber, accent);
    region.y = cursorY;
    region.h = r.y + r.h - cursorY;
  }

  if (slide.kind === 'cover' || slide.kind === 'cta') {
    // Centred, oversized title + supporting line.
    const { lines, px } = autoFit(ctx, sanitizeHebrewText(slide.title), region.w, b.W * 0.085, b.W * 0.042, 5, (c, p) => setDisplay(c, p, 800));
    setDisplay(ctx, px, 800);
    ctx.direction = 'rtl';
    ctx.textAlign = 'center';
    ctx.textBaseline = 'alphabetic';
    let y = region.y + region.h * 0.3 - ((lines.length - 1) * px * 1.18) / 2;
    for (const line of lines) {
      const grad = ctx.createLinearGradient(region.x + region.w, 0, region.x, 0);
      grad.addColorStop(0, '#FFFFFF');
      grad.addColorStop(0.55, SILVER);
      grad.addColorStop(1, accent);
      ctx.fillStyle = grad;
      ctx.fillText(line, b.W / 2, y);
      y += px * 1.18;
    }
    if (slide.body) {
      y += b.W * 0.03;
      setBody(ctx, b.W * 0.034, 400);
      ctx.fillStyle = 'rgba(226,232,240,0.85)';
      for (const line of wrapRtl(ctx, sanitizeHebrewText(slide.body), region.w * 0.9).slice(0, 5)) {
        ctx.fillText(line, b.W / 2, y);
        y += b.W * 0.048;
      }
    }
    if (slide.kind === 'cta') {
      y += b.W * 0.05;
      ctx.direction = 'ltr';
      // A Threads deck's CTA promotes the specific guide the agent matched to the topic; a deck
      // that names no target keeps the bare domain, which is what the Tech Tips CTA has always
      // drawn. A guide path is far longer than the domain, so the pill shrinks to fit the content
      // column instead of running off the slide edge.
      const target = (slide.ctaUrl ?? '').trim().replace(/^https?:\/\//i, '').replace(/\/$/, '');
      const label = `🔗  ${target || DOMAIN}`;
      let lp = b.W * 0.032;
      setDisplay(ctx, lp, 800);
      while (lp > b.W * 0.017 && ctx.measureText(label).width + b.W * 0.07 > region.w) {
        lp *= 0.94;
        setDisplay(ctx, lp, 800);
      }
      const tw = Math.min(region.w, ctx.measureText(label).width + b.W * 0.07);
      const ph = Math.max(b.W * 0.05, lp * 2.1);
      roundRectPath(ctx, b.W / 2 - tw / 2, y, tw, ph, ph / 2);
      ctx.save();
      ctx.shadowColor = accent;
      ctx.shadowBlur = 30;
      ctx.fillStyle = accent;
      ctx.fill();
      ctx.restore();
      ctx.fillStyle = '#05070A';
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      ctx.fillText(label, b.W / 2, y + ph / 2 + 1);
    }
  } else {
    const afterTitle = drawTitle(ctx, b, region, slide.title, b.W * 0.052, 3, accent) + b.W * 0.028;
    const remaining = region.y + region.h - afterTitle;

    if (slide.kind === 'code' && slide.code.trim()) {
      if (slide.body) {
        setBody(ctx, b.W * 0.028, 400);
        ctx.direction = 'rtl';
        ctx.textAlign = 'right';
        ctx.fillStyle = 'rgba(226,232,240,0.8)';
        let by = afterTitle;
        for (const line of wrapRtl(ctx, sanitizeHebrewText(slide.body), region.w).slice(0, 2)) {
          ctx.fillText(line, region.x + region.w, by);
          by += b.W * 0.04;
        }
        drawCodeBlock(ctx, b, region, slide, by + b.W * 0.015, region.y + region.h - (by + b.W * 0.015));
      } else {
        drawCodeBlock(ctx, b, region, slide, afterTitle, remaining);
      }
    } else if (slide.promptBox?.trim()) {
      // Same shape as the code branch: the body sets the prompt up in a line or two, the box is the
      // slide's actual payload. Checked after code so a slide carrying both never draws two panels.
      if (slide.body) {
        setBody(ctx, b.W * 0.028, 400);
        ctx.direction = 'rtl';
        ctx.textAlign = 'right';
        ctx.fillStyle = 'rgba(226,232,240,0.8)';
        let by = afterTitle;
        for (const line of wrapRtl(ctx, sanitizeHebrewText(slide.body), region.w).slice(0, 2)) {
          ctx.fillText(line, region.x + region.w, by);
          by += b.W * 0.04;
        }
        const boxTop = by + b.W * 0.015;
        drawPromptBox(ctx, b, region, slide.promptBox, boxTop, region.y + region.h - boxTop, accent);
      } else {
        drawPromptBox(ctx, b, region, slide.promptBox, afterTitle, remaining, accent);
      }
    } else if ((slide.kind === 'tool' || slide.kind === 'takeaway') && slide.bullets.length) {
      drawBulletList(ctx, b, region, slide.bullets, afterTitle, remaining, slide.kind === 'takeaway' ? 'check' : 'dot');
    } else {
      drawParagraph(ctx, b, region, slide.body || slide.bullets.join('. '), afterTitle, remaining);
    }
  }

  ctx.restore();
}

// ─── still carousel export ──────────────────────────────────────────────────────────────────

async function ensureFonts() {
  await Promise.all([
    loadFont('800 90px Rubik'),
    loadFont('800 56px Rubik'),
    loadFont('400 40px Heebo'),
    loadFont('500 32px Heebo'),
    loadFont("500 28px 'JetBrains Mono'"),
    loadFont("700 20px 'JetBrains Mono'"),
  ]);
}

export async function renderTipDeckImages(
  deck: TechTipDeck,
  opts: { width?: number; height?: number; backgrounds?: (HTMLImageElement | null)[] } = {},
  onProgress?: (done: number, total: number) => void
): Promise<string[]> {
  const width = opts.width ?? 1080;
  const height = opts.height ?? 1350;
  const b = boxFor(width, height);
  const logo = await getLogo();
  await ensureFonts();

  const out: string[] = [];
  for (let i = 0; i < deck.slides.length; i++) {
    const canvas = document.createElement('canvas');
    canvas.width = width;
    canvas.height = height;
    const ctx = canvas.getContext('2d');
    if (!ctx) throw new Error('canvas 2d context unavailable');
    ctx.imageSmoothingEnabled = true;
    ctx.imageSmoothingQuality = 'high';
    drawTipSlide(ctx, b, deck.slides[i], i, deck.slides.length, opts.backgrounds?.[i] ?? null, logo);
    out.push(canvas.toDataURL('image/png'));
    onProgress?.(i + 1, deck.slides.length);
  }
  return out;
}

function dataUrlToBytes(dataUrl: string): Uint8Array {
  const base64 = dataUrl.split(',')[1] ?? '';
  const bin = atob(base64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return bytes;
}

export async function exportTipDeckZip(deck: TechTipDeck, images: string[], caption: string): Promise<void> {
  const zip = new JSZip();
  const slug = (deck.title || 'tech-tip').replace(/[^\w֐-׿]+/g, '-').slice(0, 40) || 'tech-tip';
  images.forEach((img, i) => {
    const s = deck.slides[i];
    if (img && s) zip.file(`${String(i + 1).padStart(2, '0')}_${s.kind}.png`, dataUrlToBytes(img));
  });
  zip.file('caption.txt', caption);
  zip.file(
    'code-snippets.txt',
    deck.slides
      .map((s, i) => (s.code.trim() ? `--- slide ${i + 1} (${s.codeLang}) — ${s.title}\n${s.code}\n` : ''))
      .filter(Boolean)
      .join('\n')
  );
  const blob = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `mrdaniel-tips-${slug}.zip`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
