import JSZip from 'jszip';
import { loadImage, getLogo, loadFont, wrapRtl, BRAND_GREEN } from './newsImageComposer';
import { sanitizeHebrewText } from './hebrewTextSanitizer';
import { highlightCode, TOKEN_PALETTE } from './syntaxHighlight';
import type { TechTipDeck, TechTipSlide } from './techTipsApi';

/**
 * Tech Tips slide painter — dark-cyber teaching slides, drawn on <canvas> so the SAME painter
 * feeds both outputs: the still carousel PNGs and every frame of the animated reel
 * (motionStudioService.ts). Size-agnostic: pass 1080×1350 for a 4:5 carousel or 1080×1920 for a
 * 9:16 reel and the layout scales off the canvas box rather than hard-coded coordinates.
 *
 * Backgrounds are OPTIONAL and generated by Pollinations (free, keyless, CORS-open — verified) from
 * each slide's own `visualPrompt`. Off by default: generation adds seconds per slide, and every
 * slide already reads correctly on the procedural obsidian+grid backdrop, which is the fallback
 * whenever generation is disabled, slow, or fails.
 */

const OBSIDIAN_TOP = '#06080D';
const OBSIDIAN_BOTTOM = '#0B0F17';
const CYBER_CYAN = '#22D3EE';
const SILVER = '#E2E8F0';
const DOMAIN = 'mrdaniel.co.il';

export interface SlideBox {
  W: number;
  H: number;
  PAD: number;
}

export function boxFor(width: number, height: number): SlideBox {
  return { W: width, H: height, PAD: Math.round(width * 0.085) };
}

// ─── background ─────────────────────────────────────────────────────────────────────────────

function hexToRgba(hex: string, a: number): string {
  const n = parseInt(hex.replace('#', ''), 16);
  return `rgba(${(n >> 16) & 255},${(n >> 8) & 255},${n & 255},${a})`;
}

function paintProceduralBackground(ctx: CanvasRenderingContext2D, b: SlideBox, seed: number) {
  const g = ctx.createLinearGradient(0, 0, b.W * 0.4, b.H);
  g.addColorStop(0, OBSIDIAN_TOP);
  g.addColorStop(1, OBSIDIAN_BOTTOM);
  ctx.fillStyle = g;
  ctx.fillRect(0, 0, b.W, b.H);

  // carbon grid
  ctx.save();
  ctx.strokeStyle = 'rgba(226,232,240,0.035)';
  ctx.lineWidth = 1;
  const step = Math.round(b.W / 10);
  for (let x = step; x < b.W; x += step) {
    ctx.beginPath();
    ctx.moveTo(x + 0.5, 0);
    ctx.lineTo(x + 0.5, b.H);
    ctx.stroke();
  }
  for (let y = step; y < b.H; y += step) {
    ctx.beginPath();
    ctx.moveTo(0, y + 0.5);
    ctx.lineTo(b.W, y + 0.5);
    ctx.stroke();
  }
  ctx.restore();

  // ambient accent glow, seeded so consecutive slides differ
  const cx = b.W * (0.3 + ((seed * 37) % 40) / 100);
  const cy = b.H * (0.25 + ((seed * 53) % 45) / 100);
  const rg = ctx.createRadialGradient(cx, cy, 0, cx, cy, b.W * 0.75);
  rg.addColorStop(0, hexToRgba(seed % 2 === 0 ? BRAND_GREEN : CYBER_CYAN, 0.14));
  rg.addColorStop(1, 'rgba(0,0,0,0)');
  ctx.fillStyle = rg;
  ctx.fillRect(0, 0, b.W, b.H);
}

/** Pollinations: free + keyless + `Access-Control-Allow-Origin: *` (verified), so the generated
 * image can be drawn to canvas without tainting it. */
export function pollinationsUrl(prompt: string, width: number, height: number, seed: number): string {
  const p = encodeURIComponent(prompt.slice(0, 380));
  return `https://image.pollinations.ai/prompt/${p}?width=${width}&height=${height}&nologo=true&seed=${seed}`;
}

/** Resolves one AI backdrop per slide. Bounded concurrency + per-image timeout; any failure just
 * yields null and the slide falls back to the procedural backdrop. */
export async function resolveTipBackgrounds(
  deck: TechTipDeck,
  width: number,
  height: number,
  onProgress?: (done: number, total: number) => void
): Promise<(HTMLImageElement | null)[]> {
  const total = deck.slides.length;
  const out: (HTMLImageElement | null)[] = new Array(total).fill(null);
  let done = 0;
  let cursor = 0;
  const workers = Array.from({ length: Math.min(3, total) }, async () => {
    while (cursor < total) {
      const i = cursor++;
      const slide = deck.slides[i];
      const prompt = slide.visualPrompt || 'abstract dark cyber technology grid, neon green accents, no text';
      out[i] = await Promise.race([
        loadImage(pollinationsUrl(prompt, Math.round(width / 2), Math.round(height / 2), i + 7)),
        new Promise<null>((r) => setTimeout(() => r(null), 30000)),
      ]);
      done++;
      onProgress?.(done, total);
    }
  });
  await Promise.all(workers);
  return out;
}

function drawBackgroundImage(ctx: CanvasRenderingContext2D, b: SlideBox, img: HTMLImageElement) {
  const iw = img.naturalWidth;
  const ih = img.naturalHeight;
  if (!iw || !ih) return;
  const canvasRatio = b.W / b.H;
  const imgRatio = iw / ih;
  let sw: number, sh: number, sx: number, sy: number;
  if (imgRatio > canvasRatio) {
    sh = ih;
    sw = sh * canvasRatio;
    sx = (iw - sw) / 2;
    sy = 0;
  } else {
    sw = iw;
    sh = sw / canvasRatio;
    sx = 0;
    sy = (ih - sh) / 2;
  }
  ctx.drawImage(img, sx, sy, sw, sh, 0, 0, b.W, b.H);
  // Heavy scrim: the AI backdrop is texture, never competition for the teaching content.
  ctx.fillStyle = 'rgba(6,8,13,0.78)';
  ctx.fillRect(0, 0, b.W, b.H);
}

// ─── chrome ─────────────────────────────────────────────────────────────────────────────────

function roundRectPath(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, r: number) {
  const rr = Math.max(0, Math.min(r, w / 2, h / 2));
  ctx.beginPath();
  ctx.moveTo(x + rr, y);
  ctx.arcTo(x + w, y, x + w, y + h, rr);
  ctx.arcTo(x + w, y + h, x, y + h, rr);
  ctx.arcTo(x, y + h, x, y, rr);
  ctx.arcTo(x, y, x + w, y, rr);
  ctx.closePath();
}

function glassPanel(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, r: number, accent?: string) {
  ctx.save();
  ctx.shadowColor = 'rgba(0,0,0,0.5)';
  ctx.shadowBlur = 36;
  ctx.shadowOffsetY = 18;
  roundRectPath(ctx, x, y, w, h, r);
  ctx.fillStyle = 'rgba(255,255,255,0.035)';
  ctx.fill();
  ctx.restore();
  roundRectPath(ctx, x, y, w, h, r);
  ctx.strokeStyle = accent ? hexToRgba(accent, 0.35) : 'rgba(255,255,255,0.10)';
  ctx.lineWidth = 1.5;
  ctx.stroke();
}

const setDisplay = (ctx: CanvasRenderingContext2D, px: number, w = 800) => {
  ctx.font = `${w} ${Math.round(px)}px Rubik, Heebo, sans-serif`;
};
const setBody = (ctx: CanvasRenderingContext2D, px: number, w = 400) => {
  ctx.font = `${w} ${Math.round(px)}px Heebo, Rubik, sans-serif`;
};
const setMono = (ctx: CanvasRenderingContext2D, px: number, w = 500) => {
  ctx.font = `${w} ${Math.round(px)}px 'JetBrains Mono', 'Heebo', monospace`;
};

function autoFit(
  ctx: CanvasRenderingContext2D,
  text: string,
  maxW: number,
  startPx: number,
  minPx: number,
  maxLines: number,
  set: (c: CanvasRenderingContext2D, px: number) => void
): { lines: string[]; px: number } {
  let px = startPx;
  let lines: string[] = [];
  for (let i = 0; i < 24; i++) {
    set(ctx, px);
    lines = wrapRtl(ctx, text, maxW);
    if (lines.length <= maxLines || px <= minPx) break;
    px = Math.max(minPx, px * 0.93);
  }
  return { lines, px };
}

function drawTopBar(ctx: CanvasRenderingContext2D, b: SlideBox, slide: TechTipSlide, index: number, total: number, logo: HTMLImageElement | null) {
  const y = Math.round(b.H * 0.045);
  // index, left (LTR)
  ctx.save();
  ctx.direction = 'ltr';
  ctx.textAlign = 'left';
  ctx.textBaseline = 'middle';
  setMono(ctx, b.W * 0.019, 600);
  ctx.fillStyle = 'rgba(226,232,240,0.55)';
  ctx.fillText(`${String(index + 1).padStart(2, '0')} / ${String(total).padStart(2, '0')}`, b.PAD, y);
  ctx.restore();

  // kicker chip, right (RTL)
  const kicker = sanitizeHebrewText(slide.kicker || '');
  if (kicker) {
    ctx.save();
    ctx.direction = 'rtl';
    ctx.textAlign = 'right';
    ctx.textBaseline = 'middle';
    setMono(ctx, b.W * 0.018, 600);
    const kw = ctx.measureText(kicker).width + b.W * 0.035;
    const kh = b.W * 0.038;
    const kx = b.W - b.PAD - kw;
    roundRectPath(ctx, kx, y - kh / 2, kw, kh, kh * 0.28);
    ctx.fillStyle = hexToRgba(BRAND_GREEN, 0.12);
    ctx.fill();
    ctx.strokeStyle = hexToRgba(BRAND_GREEN, 0.45);
    ctx.lineWidth = 1;
    ctx.stroke();
    ctx.fillStyle = '#9FE870';
    ctx.fillText(kicker, b.W - b.PAD - b.W * 0.017, y + 1);
    ctx.restore();
  }

  if (logo) {
    const h = b.W * 0.032;
    const w = h * (logo.naturalWidth / logo.naturalHeight || 3);
    ctx.save();
    ctx.globalAlpha = 0.85;
    ctx.drawImage(logo, b.W / 2 - w / 2, y - h / 2, w, h);
    ctx.restore();
  }
}

function drawBottomBar(ctx: CanvasRenderingContext2D, b: SlideBox, index: number, total: number) {
  const railY = b.H - b.PAD * 1.15;
  const gap = 7;
  const railW = b.W - b.PAD * 2;
  const segW = (railW - gap * (total - 1)) / total;
  for (let i = 0; i < total; i++) {
    const x = b.PAD + i * (segW + gap);
    roundRectPath(ctx, x, railY, Math.max(2, segW), 5, 2.5);
    ctx.fillStyle = i <= index ? BRAND_GREEN : 'rgba(255,255,255,0.14)';
    ctx.fill();
  }
  ctx.save();
  ctx.direction = 'ltr';
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';
  setMono(ctx, b.W * 0.019, 600);
  ctx.fillStyle = 'rgba(226,232,240,0.6)';
  ctx.fillText(DOMAIN, b.W / 2, b.H - b.PAD * 0.5);
  ctx.restore();
}

// ─── per-kind bodies ────────────────────────────────────────────────────────────────────────

interface Region {
  x: number;
  y: number;
  w: number;
  h: number;
}

function contentRegion(b: SlideBox): Region {
  const top = b.H * 0.14;
  const bottom = b.H - b.PAD * 1.9;
  return { x: b.PAD, y: top, w: b.W - b.PAD * 2, h: bottom - top };
}

function drawTitle(ctx: CanvasRenderingContext2D, b: SlideBox, r: Region, title: string, startPx: number, maxLines: number): number {
  if (!title) return r.y;
  const { lines, px } = autoFit(ctx, sanitizeHebrewText(title), r.w, startPx, b.W * 0.032, maxLines, (c, p) => setDisplay(c, p, 800));
  setDisplay(ctx, px, 800);
  ctx.direction = 'rtl';
  ctx.textAlign = 'right';
  ctx.textBaseline = 'alphabetic';
  let y = r.y + px;
  for (const line of lines) {
    const grad = ctx.createLinearGradient(r.x + r.w, 0, r.x, 0);
    grad.addColorStop(0, '#FFFFFF');
    grad.addColorStop(0.6, SILVER);
    grad.addColorStop(1, CYBER_CYAN);
    ctx.fillStyle = grad;
    ctx.fillText(line, r.x + r.w, y);
    y += px * 1.18;
  }
  return y;
}

function drawParagraph(ctx: CanvasRenderingContext2D, b: SlideBox, r: Region, text: string, top: number, maxH: number) {
  if (!text) return;
  const { lines, px } = autoFit(ctx, sanitizeHebrewText(text), r.w - b.W * 0.06, b.W * 0.038, b.W * 0.022, 14, (c, p) => setBody(c, p, 400));
  const lh = px * 1.55;
  const panelH = Math.min(maxH, lines.length * lh + b.W * 0.075);
  glassPanel(ctx, r.x, top, r.w, panelH, b.W * 0.028);
  setBody(ctx, px, 400);
  ctx.fillStyle = 'rgba(255,255,255,0.94)';
  ctx.direction = 'rtl';
  ctx.textAlign = 'right';
  let y = top + b.W * 0.045 + px;
  for (const line of lines) {
    if (y > top + panelH - b.W * 0.01) break;
    ctx.fillText(line, r.x + r.w - b.W * 0.03, y);
    y += lh;
  }
}

function drawCodeBlock(ctx: CanvasRenderingContext2D, b: SlideBox, r: Region, slide: TechTipSlide, top: number, maxH: number) {
  const lines = highlightCode(slide.code, slide.codeLang);
  const panelH = maxH;
  glassPanel(ctx, r.x, top, r.w, panelH, b.W * 0.024, CYBER_CYAN);

  // window chrome + language tag
  ctx.save();
  for (let i = 0; i < 3; i++) {
    ctx.beginPath();
    ctx.arc(r.x + b.W * 0.032 + i * b.W * 0.022, top + b.W * 0.032, b.W * 0.0055, 0, Math.PI * 2);
    ctx.fillStyle = ['#F87171', '#FBBF24', '#34D399'][i];
    ctx.fill();
  }
  ctx.direction = 'ltr';
  ctx.textAlign = 'right';
  ctx.textBaseline = 'middle';
  setMono(ctx, b.W * 0.017, 700);
  ctx.fillStyle = hexToRgba(CYBER_CYAN, 0.85);
  ctx.fillText((slide.codeLang || 'code').toUpperCase(), r.x + r.w - b.W * 0.028, top + b.W * 0.032);
  ctx.restore();

  // Fit the snippet: shrink until every line fits both the panel height AND its width.
  const innerTop = top + b.W * 0.062;
  const innerH = panelH - b.W * 0.078;
  const innerW = r.w - b.W * 0.075;
  let px = b.W * 0.026;
  const minPx = b.W * 0.0135;
  for (let i = 0; i < 24; i++) {
    setMono(ctx, px, 500);
    const widest = lines.reduce((m, toks) => Math.max(m, ctx.measureText(toks.map((t) => t.text).join('')).width), 0);
    if ((lines.length * px * 1.5 <= innerH && widest <= innerW) || px <= minPx) break;
    px = Math.max(minPx, px * 0.94);
  }
  setMono(ctx, px, 500);
  const lh = px * 1.5;

  ctx.save();
  ctx.direction = 'ltr';
  ctx.textAlign = 'left';
  ctx.textBaseline = 'alphabetic';
  let y = innerTop + px;
  const gutterW = px * 2.2;
  for (let i = 0; i < lines.length; i++) {
    if (y > innerTop + innerH) break;
    // line number gutter
    ctx.fillStyle = 'rgba(148,163,184,0.35)';
    ctx.fillText(String(i + 1).padStart(2, ' '), r.x + b.W * 0.028, y);
    // tokens
    let x = r.x + b.W * 0.028 + gutterW;
    for (const tok of lines[i]) {
      ctx.fillStyle = TOKEN_PALETTE[tok.color];
      ctx.fillText(tok.text, x, y);
      x += ctx.measureText(tok.text).width;
    }
    y += lh;
  }
  ctx.restore();
}

function drawBulletList(ctx: CanvasRenderingContext2D, b: SlideBox, r: Region, bullets: string[], top: number, maxH: number, marker: 'check' | 'dot') {
  const items = bullets.slice(0, 5);
  if (!items.length) return;
  const rowH = Math.min(b.W * 0.16, maxH / items.length);
  let y = top;
  for (const raw of items) {
    const h = rowH - b.W * 0.014;
    glassPanel(ctx, r.x, y, r.w, h, b.W * 0.02);
    const boxS = b.W * 0.037;
    const bx = r.x + r.w - b.W * 0.032 - boxS;
    const by = y + h / 2 - boxS / 2;
    if (marker === 'check') {
      roundRectPath(ctx, bx, by, boxS, boxS, boxS * 0.25);
      ctx.fillStyle = hexToRgba(BRAND_GREEN, 0.16);
      ctx.fill();
      ctx.strokeStyle = BRAND_GREEN;
      ctx.lineWidth = 2;
      ctx.stroke();
      ctx.save();
      ctx.strokeStyle = BRAND_GREEN;
      ctx.lineWidth = boxS * 0.11;
      ctx.lineCap = 'round';
      ctx.beginPath();
      ctx.moveTo(bx + boxS * 0.26, by + boxS * 0.52);
      ctx.lineTo(bx + boxS * 0.45, by + boxS * 0.72);
      ctx.lineTo(bx + boxS * 0.76, by + boxS * 0.3);
      ctx.stroke();
      ctx.restore();
    } else {
      ctx.beginPath();
      ctx.arc(bx + boxS / 2, by + boxS / 2, boxS * 0.22, 0, Math.PI * 2);
      ctx.fillStyle = CYBER_CYAN;
      ctx.fill();
    }
    ctx.direction = 'rtl';
    ctx.textAlign = 'right';
    ctx.textBaseline = 'alphabetic';
    const { lines, px } = autoFit(ctx, sanitizeHebrewText(raw), r.w - boxS - b.W * 0.09, b.W * 0.03, b.W * 0.02, 2, (c, p) => setBody(c, p, 500));
    setBody(ctx, px, 500);
    ctx.fillStyle = 'rgba(255,255,255,0.95)';
    let ty = y + h / 2 - ((lines.length - 1) * px * 1.3) / 2 + px * 0.34;
    for (const line of lines) {
      ctx.fillText(line, bx - b.W * 0.022, ty);
      ty += px * 1.3;
    }
    y += rowH;
  }
}

function drawStepBadge(ctx: CanvasRenderingContext2D, b: SlideBox, r: Region, n: number): number {
  const size = b.W * 0.115;
  const x = r.x + r.w - size;
  const y = r.y;
  ctx.save();
  roundRectPath(ctx, x, y, size, size, size * 0.28);
  ctx.fillStyle = hexToRgba(BRAND_GREEN, 0.14);
  ctx.fill();
  ctx.strokeStyle = hexToRgba(BRAND_GREEN, 0.55);
  ctx.lineWidth = 2;
  ctx.stroke();
  ctx.direction = 'ltr';
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';
  setDisplay(ctx, size * 0.52, 900);
  ctx.fillStyle = BRAND_GREEN;
  ctx.shadowColor = BRAND_GREEN;
  ctx.shadowBlur = 18;
  ctx.fillText(String(n), x + size / 2, y + size / 2 + 2);
  ctx.restore();
  return y + size + b.W * 0.03;
}

// ─── main painter ───────────────────────────────────────────────────────────────────────────

export interface SlideAnim {
  /** 0..1 entrance progress — drives the fade/rise of the slide's body content. */
  intro: number;
  /** 0..1 crossfade-out at the end of a scene (motion export only). */
  outro: number;
}

export function drawTipSlide(
  ctx: CanvasRenderingContext2D,
  b: SlideBox,
  slide: TechTipSlide,
  index: number,
  total: number,
  bg: HTMLImageElement | null,
  logo: HTMLImageElement | null,
  anim: SlideAnim = { intro: 1, outro: 0 }
) {
  ctx.clearRect(0, 0, b.W, b.H);
  paintProceduralBackground(ctx, b, index);
  if (bg) drawBackgroundImage(ctx, b, bg);

  drawTopBar(ctx, b, slide, index, total, logo);
  drawBottomBar(ctx, b, index, total);

  const r = contentRegion(b);
  const alpha = Math.max(0, Math.min(1, anim.intro)) * (1 - Math.max(0, Math.min(1, anim.outro)));
  const rise = (1 - Math.min(1, anim.intro)) * b.W * 0.02;

  ctx.save();
  ctx.globalAlpha = alpha;
  ctx.translate(0, rise);

  const region: Region = { ...r };
  let cursorY = region.y;

  if (slide.kind === 'step' && slide.stepNumber > 0) {
    cursorY = drawStepBadge(ctx, b, region, slide.stepNumber);
    region.y = cursorY;
    region.h = r.y + r.h - cursorY;
  }

  if (slide.kind === 'cover' || slide.kind === 'cta') {
    // Centred, oversized title + supporting line.
    const { lines, px } = autoFit(ctx, sanitizeHebrewText(slide.title), region.w, b.W * 0.085, b.W * 0.042, 5, (c, p) => setDisplay(c, p, 800));
    setDisplay(ctx, px, 800);
    ctx.direction = 'rtl';
    ctx.textAlign = 'center';
    ctx.textBaseline = 'alphabetic';
    let y = region.y + region.h * 0.3 - ((lines.length - 1) * px * 1.18) / 2;
    for (const line of lines) {
      const grad = ctx.createLinearGradient(region.x + region.w, 0, region.x, 0);
      grad.addColorStop(0, '#FFFFFF');
      grad.addColorStop(0.55, SILVER);
      grad.addColorStop(1, slide.kind === 'cta' ? BRAND_GREEN : CYBER_CYAN);
      ctx.fillStyle = grad;
      ctx.fillText(line, b.W / 2, y);
      y += px * 1.18;
    }
    if (slide.body) {
      y += b.W * 0.03;
      setBody(ctx, b.W * 0.034, 400);
      ctx.fillStyle = 'rgba(226,232,240,0.85)';
      for (const line of wrapRtl(ctx, sanitizeHebrewText(slide.body), region.w * 0.9).slice(0, 5)) {
        ctx.fillText(line, b.W / 2, y);
        y += b.W * 0.048;
      }
    }
    if (slide.kind === 'cta') {
      y += b.W * 0.05;
      setDisplay(ctx, b.W * 0.032, 800);
      ctx.direction = 'ltr';
      const label = `🔗  ${DOMAIN}`;
      const tw = ctx.measureText(label).width + b.W * 0.07;
      const ph = b.W * 0.068;
      roundRectPath(ctx, b.W / 2 - tw / 2, y, tw, ph, ph / 2);
      ctx.save();
      ctx.shadowColor = BRAND_GREEN;
      ctx.shadowBlur = 30;
      ctx.fillStyle = BRAND_GREEN;
      ctx.fill();
      ctx.restore();
      ctx.fillStyle = '#05070A';
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      ctx.fillText(label, b.W / 2, y + ph / 2 + 1);
    }
  } else {
    const afterTitle = drawTitle(ctx, b, region, slide.title, b.W * 0.052, 3) + b.W * 0.028;
    const remaining = region.y + region.h - afterTitle;

    if (slide.kind === 'code' && slide.code.trim()) {
      if (slide.body) {
        setBody(ctx, b.W * 0.028, 400);
        ctx.direction = 'rtl';
        ctx.textAlign = 'right';
        ctx.fillStyle = 'rgba(226,232,240,0.8)';
        let by = afterTitle;
        for (const line of wrapRtl(ctx, sanitizeHebrewText(slide.body), region.w).slice(0, 2)) {
          ctx.fillText(line, region.x + region.w, by);
          by += b.W * 0.04;
        }
        drawCodeBlock(ctx, b, region, slide, by + b.W * 0.015, region.y + region.h - (by + b.W * 0.015));
      } else {
        drawCodeBlock(ctx, b, region, slide, afterTitle, remaining);
      }
    } else if ((slide.kind === 'tool' || slide.kind === 'takeaway') && slide.bullets.length) {
      drawBulletList(ctx, b, region, slide.bullets, afterTitle, remaining, slide.kind === 'takeaway' ? 'check' : 'dot');
    } else {
      drawParagraph(ctx, b, region, slide.body || slide.bullets.join('. '), afterTitle, remaining);
    }
  }

  ctx.restore();
}

// ─── still carousel export ──────────────────────────────────────────────────────────────────

async function ensureFonts() {
  await Promise.all([
    loadFont('800 90px Rubik'),
    loadFont('800 56px Rubik'),
    loadFont('400 40px Heebo'),
    loadFont('500 32px Heebo'),
    loadFont("500 28px 'JetBrains Mono'"),
    loadFont("700 20px 'JetBrains Mono'"),
  ]);
}

export async function renderTipDeckImages(
  deck: TechTipDeck,
  opts: { width?: number; height?: number; backgrounds?: (HTMLImageElement | null)[] } = {},
  onProgress?: (done: number, total: number) => void
): Promise<string[]> {
  const width = opts.width ?? 1080;
  const height = opts.height ?? 1350;
  const b = boxFor(width, height);
  const logo = await getLogo();
  await ensureFonts();

  const out: string[] = [];
  for (let i = 0; i < deck.slides.length; i++) {
    const canvas = document.createElement('canvas');
    canvas.width = width;
    canvas.height = height;
    const ctx = canvas.getContext('2d');
    if (!ctx) throw new Error('canvas 2d context unavailable');
    ctx.imageSmoothingEnabled = true;
    ctx.imageSmoothingQuality = 'high';
    drawTipSlide(ctx, b, deck.slides[i], i, deck.slides.length, opts.backgrounds?.[i] ?? null, logo);
    out.push(canvas.toDataURL('image/png'));
    onProgress?.(i + 1, deck.slides.length);
  }
  return out;
}

function dataUrlToBytes(dataUrl: string): Uint8Array {
  const base64 = dataUrl.split(',')[1] ?? '';
  const bin = atob(base64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return bytes;
}

export async function exportTipDeckZip(deck: TechTipDeck, images: string[], caption: string): Promise<void> {
  const zip = new JSZip();
  const slug = (deck.title || 'tech-tip').replace(/[^\w֐-׿]+/g, '-').slice(0, 40) || 'tech-tip';
  images.forEach((img, i) => {
    const s = deck.slides[i];
    if (img && s) zip.file(`${String(i + 1).padStart(2, '0')}_${s.kind}.png`, dataUrlToBytes(img));
  });
  zip.file('caption.txt', caption);
  zip.file(
    'code-snippets.txt',
    deck.slides
      .map((s, i) => (s.code.trim() ? `--- slide ${i + 1} (${s.codeLang}) — ${s.title}\n${s.code}\n` : ''))
      .filter(Boolean)
      .join('\n')
  );
  const blob = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `mrdaniel-tips-${slug}.zip`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
