import { getNewsItems } from '../src/server/newsFeed.js';

// Vercel Serverless Function. Written as `.ts` (not `.js`) deliberately: Vercel's Node builder
// only bundles a function's dependency graph when the entry file itself is TypeScript — a plain
// `.js` entry is deployed as-is with no bundling, so Node's native ESM loader can't resolve the
// extensionless import into this repo's `src/server` TypeScript module (confirmed via a
// FUNCTION_INVOCATION_FAILED / ERR_MODULE_NOT_FOUND at runtime when this was first tried as
// `api/news.js`).
//
// CORS is open (`*`) so the analytics dashboard — served from its own origin — can read the feed
// directly for the news-driven content generator. The payload is public, read-only news metadata.
//
// The response is the SANITIZED Hebrew AI/cyber/cloud stream BY DEFAULT (see `sanitizeAndKeep` in
// newsFeed.ts) — Hebrew-only titles, no scrape/parse artefacts, on-topic only. `?strict=0` (or
// `?strict=false`) returns the raw unfiltered aggregate for debugging. Vercel's edge caches the
// two URL variants under separate keys, so they never mix.
//
// This function ALSO serves `POST /api/news/analyze` (rewritten here as `?action=analyze` in
// vercel.json) — the per-article Gemini analysis behind the modal's "ניתוח טכנולוגי ומשמעויות"
// block. It shares this entry rather than getting its own file because the Hobby plan caps a
// deployment at 12 Serverless Functions; `src/server/newsInsights.ts` (and with it @google/genai)
// is pulled in through a dynamic import so a plain feed GET never pays for loading it.
export default async function handler(req: any, res: any) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.query?.action === 'analyze' || req.method === 'POST') {
    await handleAnalyze(req, res);
    return;
  }

  // Short CDN cache + stale-while-revalidate: viewers get an instant response and the edge
  // refreshes the feed in the background, so the News Content Agent streams new stories through
  // the day without every client hammering the origin. `Vercel-CDN-Cache-Control` is the
  // directive Vercel's edge actually honours (plain `s-maxage` gets stripped for functions).
  res.setHeader('Cache-Control', 'public, max-age=120');
  res.setHeader('Vercel-CDN-Cache-Control', 'max-age=600, stale-while-revalidate=1800');
  if (req.method === 'OPTIONS') {
    res.status(204).end();
    return;
  }

  try {
    // Sanitized Hebrew stream by default; `?strict=0` / `?strict=false` opts out to the raw feed.
    const strictRaw = String((req.query?.strict ?? '')).toLowerCase();
    const strict = !(strictRaw === '0' || strictRaw === 'false' || strictRaw === 'no');
    const data = await getNewsItems({ strict });
    res.status(200).json(data);
  } catch (err) {
    console.error('[api/news] failed to fetch news items:', err);
    res.status(500).json({ error: 'failed to fetch news' });
  }
}

/**
 * `POST /api/news/analyze` — 3 insights generated by Gemini from THIS article's title and body.
 * There is no boilerplate fallback anywhere in this path: an unconfigured key, a rate limit or an
 * unusable model response all answer `available: false`, and the modal hides the section.
 */
async function handleAnalyze(req: any, res: any) {
  if (req.method === 'OPTIONS') {
    res.status(204).end();
    return;
  }
  if (req.method !== 'POST') {
    res.status(405).json({ error: 'method not allowed', available: false });
    return;
  }

  const { generateArticleInsights, isInsightsConfigured } = await import('../src/server/newsInsights.js');
  if (!isInsightsConfigured()) {
    res.status(503).json({ error: 'analysis unavailable', available: false });
    return;
  }

  const body: Record<string, unknown> = typeof req.body === 'string' ? safeParse(req.body) : req.body ?? {};

  try {
    const insights = await generateArticleInsights({
      title: String(body.title || ''),
      summary: String(body.summary || ''),
      excerpt: String(body.excerpt || ''),
      source: String(body.source || ''),
      topic: String(body.topic || 'general'),
      link: String(body.link || ''),
    });
    // Deterministic per article for the memo window, so the edge may hold it too.
    res.setHeader('Cache-Control', 'public, max-age=300');
    res.setHeader('Vercel-CDN-Cache-Control', 'max-age=3600, stale-while-revalidate=21600');
    res.status(200).json({ available: true, insights });
  } catch (err) {
    console.error('[api/news?action=analyze] failed to generate article insights:', err);
    const message = err instanceof Error ? err.message : 'unknown error';
    const rateLimited = /429|quota|rate.?limit|RESOURCE_EXHAUSTED/i.test(message);
    res.status(rateLimited ? 429 : 502).json({ error: message, available: false, rateLimited });
  }
}

function safeParse(raw: string): Record<string, unknown> {
  try {
    return JSON.parse(raw);
  } catch {
    return {};
  }
}
