import { getNewsItems } from '../src/server/newsFeed.js';
import {
  findStaticGuide, staticGuideMeta, GUIDE_SLUG_RE, type StaticGuide,
  findCampaignGuide, campaignGuideMeta,
} from '../src/server/leadMagnets.js';
import { readCommentDmCampaigns } from '../src/agent/firebaseServer.js';

// Vercel Serverless Function. Written as `.ts` (not `.js`) deliberately: Vercel's Node builder
// only bundles a function's dependency graph when the entry file itself is TypeScript — a plain
// `.js` entry is deployed as-is with no bundling, so Node's native ESM loader can't resolve the
// extensionless import into this repo's `src/server` TypeScript module (confirmed via a
// FUNCTION_INVOCATION_FAILED / ERR_MODULE_NOT_FOUND at runtime when this was first tried as
// `api/news.js`).
//
// CORS is open (`*`) so the analytics dashboard — served from its own origin — can read the feed
// directly for the news-driven content generator. The payload is public, read-only news metadata.
//
// The response is the SANITIZED Hebrew AI/cyber/cloud stream BY DEFAULT (see `sanitizeAndKeep` in
// newsFeed.ts) — Hebrew-only titles, no scrape/parse artefacts, on-topic only. `?strict=0` (or
// `?strict=false`) returns the raw unfiltered aggregate for debugging. Vercel's edge caches the
// two URL variants under separate keys, so they never mix.
//
// This function ALSO serves `POST /api/news/analyze` (rewritten here as `?action=analyze` in
// vercel.json) — the per-article Gemini analysis behind the modal's "ניתוח טכנולוגי ומשמעויות"
// block. It shares this entry rather than getting its own file because the Hobby plan caps a
// deployment at 12 Serverless Functions; `src/server/newsInsights.ts` (and with it @google/genai)
// is pulled in through a dynamic import so a plain feed GET never pays for loading it.
export default async function handler(req: any, res: any) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  // `GET /api/download/:guideId` is rewritten here as `?action=download&guideId=...` (vercel.json).
  // Checked before the analyze branch because that branch claims every POST.
  if (req.query?.action === 'download') {
    await handleDownload(req, res);
    return;
  }

  if (req.query?.action === 'analyze' || req.method === 'POST') {
    await handleAnalyze(req, res);
    return;
  }

  // Short CDN cache + stale-while-revalidate: viewers get an instant response and the edge
  // refreshes the feed in the background, so the News Content Agent streams new stories through
  // the day without every client hammering the origin. `Vercel-CDN-Cache-Control` is the
  // directive Vercel's edge actually honours (plain `s-maxage` gets stripped for functions).
  res.setHeader('Cache-Control', 'public, max-age=120');
  res.setHeader('Vercel-CDN-Cache-Control', 'max-age=600, stale-while-revalidate=1800');
  if (req.method === 'OPTIONS') {
    res.status(204).end();
    return;
  }

  try {
    // Sanitized Hebrew stream by default; `?strict=0` / `?strict=false` opts out to the raw feed.
    const strictRaw = String((req.query?.strict ?? '')).toLowerCase();
    const strict = !(strictRaw === '0' || strictRaw === 'false' || strictRaw === 'no');
    // Off by default (keeps the public site Hebrew-only) — `?allowEnglish=1` lets the curated
    // English specialist outlets (AWS/Azure/GCP/OpenAI/…) through, for the dashboard's tabs.
    const allowEnglishRaw = String((req.query?.allowEnglish ?? '')).toLowerCase();
    const allowEnglish = allowEnglishRaw === '1' || allowEnglishRaw === 'true';
    const data = await getNewsItems({ strict, allowEnglish });
    res.status(200).json(data);
  } catch (err) {
    console.error('[api/news] failed to fetch news items:', err);
    res.status(500).json({ error: 'failed to fetch news' });
  }
}

/**
 * `POST /api/news/analyze` — 3 insights generated by Gemini from THIS article's title and body.
 * There is no boilerplate fallback anywhere in this path: an unconfigured key, a rate limit or an
 * unusable model response all answer `available: false`, and the modal hides the section.
 */
async function handleAnalyze(req: any, res: any) {
  if (req.method === 'OPTIONS') {
    res.status(204).end();
    return;
  }
  if (req.method !== 'POST') {
    res.status(405).json({ error: 'method not allowed', available: false });
    return;
  }

  const { generateArticleInsights, isInsightsConfigured } = await import('../src/server/newsInsights.js');
  if (!isInsightsConfigured()) {
    res.status(503).json({ error: 'analysis unavailable', available: false });
    return;
  }

  const body: Record<string, unknown> = typeof req.body === 'string' ? safeParse(req.body) : req.body ?? {};

  try {
    const insights = await generateArticleInsights({
      title: String(body.title || ''),
      summary: String(body.summary || ''),
      excerpt: String(body.excerpt || ''),
      source: String(body.source || ''),
      topic: String(body.topic || 'general'),
      link: String(body.link || ''),
    });
    // Deterministic per article for the memo window, so the edge may hold it too.
    res.setHeader('Cache-Control', 'public, max-age=300');
    res.setHeader('Vercel-CDN-Cache-Control', 'max-age=3600, stale-while-revalidate=21600');
    res.status(200).json({ available: true, insights });
  } catch (err) {
    console.error('[api/news?action=analyze] failed to generate article insights:', err);
    const message = err instanceof Error ? err.message : 'unknown error';
    // A locally paced-out call is a 429 too: same meaning to the client ("too fast, retry"), but it
    // comes back immediately instead of burning the function's remaining time on a wait.
    const pacedOut = /gemini pacing:/.test(message);
    const rateLimited = pacedOut || /429|quota|rate.?limit|RESOURCE_EXHAUSTED/i.test(message);
    if (pacedOut) {
      const seconds = Number(message.match(/is (\d+)s away/)?.[1]);
      if (Number.isFinite(seconds)) res.setHeader('Retry-After', String(seconds));
    }
    res.status(rateLimited ? 429 : 502).json({ error: message, available: false, rateLimited, pacedOut });
  }
}

function safeParse(raw: string): Record<string, unknown> {
  try {
    return JSON.parse(raw);
  } catch {
    return {};
  }
}

/**
 * `GET /api/download/:guideId` — public, unauthenticated guide download.
 *
 * Two kinds of id: a static-guide slug from src/server/leadMagnets.ts (a PDF on the CDN, answered
 * without ever touching the bridge) or a bridge guideId (32 hex, resolved on the bridge below).
 *
 * Lives inside this function rather than in `api/download.ts` because the Hobby plan caps a
 * deployment at 12 Serverless Functions and `api/` is already at exactly 12; a new file would fail
 * the build. Same reason `?action=analyze` is hosted here.
 *
 * This is a ROUTER, not a proxy. It resolves the guide's metadata on the bridge and then 302s the
 * client at the bridge's own public file route, so the bytes never traverse a Vercel function —
 * a 60s maxDuration and a serverless response cap make proxying a multi-megabyte ZIP a bad idea,
 * and the bridge already serves the file with the right Content-Disposition.
 *
 * Deliberately requires NO x-admin-secret: a ManyChat button, a mail client and a link preview all
 * fetch this with no credentials. The security model is the guideId itself — 128 random bits minted
 * per publish, holding nothing but that one guide. The admin secret must never be required here,
 * and must never be *accepted* here either: this path grants no privilege.
 */
async function handleDownload(req: any, res: any) {
  if (req.method === 'OPTIONS') {
    res.status(204).end();
    return;
  }
  if (req.method !== 'GET' && req.method !== 'HEAD') {
    res.status(405).json({ ok: false, error: 'method not allowed' });
    return;
  }

  const guideId = String(req.query?.guideId || '').trim().toLowerCase();

  // Static CDN guides first: a registry slug never touches the bridge, so it keeps answering while
  // the laptop is asleep or the tunnel is down.
  const staticGuide = findStaticGuide(guideId);
  if (staticGuide) {
    handleStaticGuide(req, res, staticGuide);
    return;
  }

  if (!/^[a-f0-9]{32}$/.test(guideId)) {
    // Not a registry slug and not bridge-id-shaped: try a dashboard-authored campaign before giving
    // up. This is the zero-deploy guide path — see findCampaignGuide in leadMagnets.ts.
    const slugShaped = GUIDE_SLUG_RE.test(guideId);
    if (slugShaped) {
      const campaigns = await readCommentDmCampaigns();
      const campaignGuide = findCampaignGuide(campaigns, guideId);
      if (campaignGuide) {
        handleCampaignGuide(req, res, campaignGuide);
        return;
      }
    }
    res.status(slugShaped ? 404 : 400).json({ ok: false, error: slugShaped ? 'guide not found' : 'malformed guide id' });
    return;
  }

  const bridge = String(process.env.CAROUSEL_BRIDGE_URL || '').replace(/\/$/, '');
  if (!bridge) {
    // A misconfigured server must not look like a missing guide.
    res.status(503).json({ ok: false, error: 'download service is not configured' });
    return;
  }

  // Never cache a negative or a redirect target: the bridge sits behind an ephemeral quick-tunnel
  // whose hostname changes on every restart, so a cached 302 would outlive the URL it points at.
  res.setHeader('Cache-Control', 'no-store');

  try {
    // Resolve metadata first so we can answer 404/410 accurately instead of bouncing the client to
    // a URL that will fail. `variant` picks which artefact the redirect targets.
    const ctrl = new AbortController();
    const timer = setTimeout(() => ctrl.abort(), 8000);
    let meta: Response;
    try {
      meta = await fetch(`${bridge}/public/guide/${guideId}`, { signal: ctrl.signal });
    } finally {
      clearTimeout(timer);
    }

    if (meta.status === 404) {
      res.status(404).json({ ok: false, error: 'guide not found' });
      return;
    }
    if (meta.status === 410) {
      res.status(410).json({ ok: false, error: 'this download link has expired' });
      return;
    }
    if (!meta.ok) {
      res.status(502).json({ ok: false, error: 'download service returned an error' });
      return;
    }

    const info = (await meta.json()) as {
      title?: string;
      slides?: number;
      hasPdf?: boolean;
      topics?: string[];
      sections?: Array<{ index: number; headline: string; subhead: string; cards: string[] }>;
      createdAt?: number;
      expiresAt?: number;
    };

    const variant = String(req.query?.variant || 'zip').toLowerCase();
    let target = `${bridge}/public/download/${guideId}`;
    if (variant === 'pdf') {
      if (!info.hasPdf) {
        res.status(404).json({ ok: false, error: 'this guide has no PDF' });
        return;
      }
      target += '/pdf';
    } else if (variant === 'slide') {
      const n = Number(req.query?.n || 1);
      if (!Number.isInteger(n) || n < 1 || n > Number(info.slides || 0)) {
        res.status(404).json({ ok: false, error: 'slide out of range' });
        return;
      }
      target += `/slide/${n}`;
    }

    // `?meta=1` answers with JSON instead of redirecting — lets a ManyChat flow show the title and
    // slide count before it offers the file.
    if (String(req.query?.meta || '') === '1') {
      res.status(200).json({
        ok: true,
        kind: 'bridge',
        guideId,
        title: info.title || '',
        slides: info.slides || 0,
        hasPdf: Boolean(info.hasPdf),
        // Slide headlines, when the bridge captured them at publish time. Absent for guides
        // published before this shipped — the landing page falls back rather than rendering empty.
        topics: Array.isArray(info.topics) ? info.topics : [],
        // Real per-slide copy, when the bridge captured it at publish time. Drives the editorial
        // body on the landing page; absent for guides published before this shipped.
        sections: Array.isArray(info.sections) ? info.sections : [],
        createdAt: info.createdAt || null,
        expiresAt: info.expiresAt || null,
        downloadUrl: target,
      });
      return;
    }

    res.status(302).setHeader('Location', target);
    res.end();
  } catch (err) {
    // An unreachable bridge (tunnel down, laptop asleep) is a 503, not a 404 — the guide may well
    // exist. Saying "not found" here would send someone hunting for a link that is actually fine.
    console.error('[api/news?action=download] bridge unreachable:', err);
    res.status(503).json({ ok: false, error: 'download service is temporarily unavailable' });
  }
}

/**
 * A campaign guide (dashboard/src/components/CommentDmPanel.tsx → `comment_dm_campaigns`): content
 * lives in Firebase, not code, so — unlike handleStaticGuide — this is NOT edge-cached; a save in
 * the dashboard must be visible on the next request, not up to `s-maxage` later.
 */
function handleCampaignGuide(req: any, res: any, guide: import('../src/server/leadMagnets.js').CampaignGuide) {
  res.setHeader('Cache-Control', 'no-store');
  if (String(req.query?.meta || '') === '1') {
    res.status(200).json(campaignGuideMeta(guide));
    return;
  }
  if (String(req.query?.variant || '').toLowerCase() === 'slide') {
    res.status(404).json({ ok: false, error: 'this guide has no slide previews' });
    return;
  }
  res.status(302).setHeader('Location', guide.fileUrl);
  res.end();
}

/**
 * A registry guide (src/server/leadMagnets.ts): the PDF is a static file on the CDN, so this only
 * answers metadata or points the browser at the file. Edge-cacheable — the registry changes only
 * with a deploy, and every deploy starts with an empty cache.
 */
function handleStaticGuide(req: any, res: any, guide: StaticGuide) {
  res.setHeader('Cache-Control', 'public, max-age=0, s-maxage=300, stale-while-revalidate=86400');
  if (String(req.query?.meta || '') === '1') {
    res.status(200).json(staticGuideMeta(guide));
    return;
  }
  if (String(req.query?.variant || '').toLowerCase() === 'slide') {
    res.status(404).json({ ok: false, error: 'this guide has no slide previews' });
    return;
  }
  // The default (zip) and pdf variants both resolve to the one file a static guide has.
  res.status(302).setHeader('Location', guide.file);
  res.end();
}
